<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    public function run(): void
    {
        $badges = [
            // ── Common (9) — easy to earn ──────────────────────────────
            [
                'slug' => 'welcome',
                'names' => [
                    'en' => 'Welcome',
                    'fr' => 'Bienvenue',
                    'es' => 'Bienvenido',
                    'pt' => 'Bem-vindo',
                    'ar' => 'مرحبا',
                    'de' => 'Willkommen',
                    'zh' => '欢迎',
                    'ru' => 'Добро пожаловать',
                    'hi' => 'स्वागत है',
                ],
                'descriptions' => [
                    'en' => 'Welcome aboard! Your journey starts here.',
                    'fr' => 'Bienvenue à bord ! Ton aventure commence ici.',
                    'es' => '¡Bienvenido a bordo! Tu aventura empieza aquí.',
                    'pt' => 'Bem-vindo a bordo! Sua jornada começa aqui.',
                    'ar' => 'مرحبا بك! رحلتك تبدأ هنا.',
                    'de' => 'Willkommen an Bord! Dein Abenteuer beginnt hier.',
                    'zh' => '欢迎加入！你的旅程从这里开始。',
                    'ru' => 'Добро пожаловать! Твоё путешествие начинается здесь.',
                    'hi' => 'स्वागत है! आपकी यात्रा यहाँ से शुरू होती है।',
                ],
                'category' => 'onboarding',
                'xp_reward' => 10,
                'criteria' => ['type' => 'field', 'field' => 'id', 'count' => 0, 'rarity' => 'common'],
                'sort_order' => 1,
            ],
            [
                'slug' => 'profile_complete',
                'names' => [
                    'en' => 'Profile Complete',
                    'fr' => 'Profil Complet',
                    'es' => 'Perfil Completo',
                    'pt' => 'Perfil Completo',
                    'ar' => 'ملف مكتمل',
                    'de' => 'Profil Fertig',
                    'zh' => '资料完善',
                    'ru' => 'Профиль готов',
                    'hi' => 'प्रोफ़ाइल पूर्ण',
                ],
                'descriptions' => [
                    'en' => 'Complete your profile to get started.',
                    'fr' => 'Complète ton profil pour commencer.',
                    'es' => 'Completa tu perfil para empezar.',
                    'pt' => 'Complete seu perfil para começar.',
                    'ar' => 'أكمل ملفك الشخصي للبدء.',
                    'de' => 'Vervollständige dein Profil, um loszulegen.',
                    'zh' => '完善你的个人资料以开始使用。',
                    'ru' => 'Заполни профиль, чтобы начать.',
                    'hi' => 'शुरू करने के लिए अपनी प्रोफ़ाइल पूरी करें।',
                ],
                'category' => 'onboarding',
                'xp_reward' => 25,
                'criteria' => ['type' => 'profile_complete', 'rarity' => 'common'],
                'sort_order' => 100,
            ],
            [
                'slug' => 'first_share',
                'names' => [
                    'en' => 'First Share',
                    'fr' => 'Premier Partage',
                    'es' => 'Primer Compartido',
                    'pt' => 'Primeiro Compartilhamento',
                    'ar' => 'أول مشاركة',
                    'de' => 'Erstes Teilen',
                    'zh' => '首次分享',
                    'ru' => 'Первая публикация',
                    'hi' => 'पहला शेयर',
                ],
                'descriptions' => [
                    'en' => 'Share your affiliate link for the first time.',
                    'fr' => 'Partage ton lien affilié pour la première fois.',
                    'es' => 'Comparte tu enlace de afiliado por primera vez.',
                    'pt' => 'Compartilhe seu link de afiliado pela primeira vez.',
                    'ar' => 'شارك رابط الإحالة الخاص بك لأول مرة.',
                    'de' => 'Teile deinen Affiliate-Link zum ersten Mal.',
                    'zh' => '首次分享你的推广链接。',
                    'ru' => 'Поделись реферальной ссылкой впервые.',
                    'hi' => 'अपना एफिलिएट लिंक पहली बार शेयर करें।',
                ],
                'category' => 'social',
                'xp_reward' => 25,
                'criteria' => ['type' => 'first_share', 'rarity' => 'common'],
                'sort_order' => 101,
            ],
            [
                'slug' => 'first_client',
                'names' => [
                    'en' => 'First Client',
                    'fr' => 'Première Vente',
                    'es' => 'Primer Cliente',
                    'pt' => 'Primeiro Cliente',
                    'ar' => 'أول عميل',
                    'de' => 'Erster Kunde',
                    'zh' => '首位客户',
                    'ru' => 'Первый клиент',
                    'hi' => 'पहला ग्राहक',
                ],
                'descriptions' => [
                    'en' => 'Land your very first client.',
                    'fr' => 'Décroche ta toute première vente.',
                    'es' => 'Consigue tu primer cliente.',
                    'pt' => 'Conquiste seu primeiro cliente.',
                    'ar' => 'احصل على أول عميل لك.',
                    'de' => 'Gewinne deinen allerersten Kunden.',
                    'zh' => '获得你的第一个客户。',
                    'ru' => 'Получи своего первого клиента.',
                    'hi' => 'अपना पहला ग्राहक पाएं।',
                ],
                'category' => 'sales',
                'xp_reward' => 100,
                'criteria' => ['type' => 'sales_count', 'count' => 1, 'rarity' => 'common'],
                'sort_order' => 102,
            ],
            [
                'slug' => 'streak_7',
                'names' => [
                    'en' => 'Week Warrior',
                    'fr' => 'Guerrier de la Semaine',
                    'es' => 'Guerrero Semanal',
                    'pt' => 'Guerreiro Semanal',
                    'ar' => 'محارب الأسبوع',
                    'de' => 'Wochenkrieger',
                    'zh' => '周战士',
                    'ru' => 'Воин недели',
                    'hi' => 'सप्ताह का योद्धा',
                ],
                'descriptions' => [
                    'en' => 'Maintain a 7-day activity streak.',
                    'fr' => 'Maintiens une série d\'activité de 7 jours.',
                    'es' => 'Mantén una racha de actividad de 7 días.',
                    'pt' => 'Mantenha uma sequência de atividade de 7 dias.',
                    'ar' => 'حافظ على سلسلة نشاط لمدة 7 أيام.',
                    'de' => 'Halte eine 7-Tage-Aktivitätsserie aufrecht.',
                    'zh' => '保持7天连续活跃记录。',
                    'ru' => 'Поддерживай серию активности 7 дней.',
                    'hi' => '7 दिन की गतिविधि श्रृंखला बनाए रखें।',
                ],
                'category' => 'streak',
                'xp_reward' => 75,
                'criteria' => ['type' => 'streak', 'count' => 7, 'rarity' => 'common'],
                'sort_order' => 103,
            ],
            [
                'slug' => 'level_2',
                'names' => [
                    'en' => 'Apprentice',
                    'fr' => 'Apprenti',
                    'es' => 'Aprendiz',
                    'pt' => 'Aprendiz',
                    'ar' => 'متدرب',
                    'de' => 'Lehrling',
                    'zh' => '学徒',
                    'ru' => 'Ученик',
                    'hi' => 'शिक्षार्थी',
                ],
                'descriptions' => [
                    'en' => 'Reach level 2.',
                    'fr' => 'Atteins le niveau 2.',
                    'es' => 'Alcanza el nivel 2.',
                    'pt' => 'Alcance o nível 2.',
                    'ar' => 'ابلغ المستوى 2.',
                    'de' => 'Erreiche Level 2.',
                    'zh' => '达到等级2。',
                    'ru' => 'Достигни уровня 2.',
                    'hi' => 'लेवल 2 तक पहुंचें।',
                ],
                'category' => 'level',
                'xp_reward' => 50,
                'criteria' => ['type' => 'level', 'count' => 2, 'rarity' => 'common'],
                'sort_order' => 104,
            ],
            [
                'slug' => 'training_first',
                'names' => [
                    'en' => 'First Training',
                    'fr' => 'Première Formation',
                    'es' => 'Primera Formación',
                    'pt' => 'Primeiro Treinamento',
                    'ar' => 'أول تدريب',
                    'de' => 'Erstes Training',
                    'zh' => '首次培训',
                    'ru' => 'Первое обучение',
                    'hi' => 'पहला प्रशिक्षण',
                ],
                'descriptions' => [
                    'en' => 'Complete your first training module.',
                    'fr' => 'Termine ton premier module de formation.',
                    'es' => 'Completa tu primer módulo de formación.',
                    'pt' => 'Complete seu primeiro módulo de treinamento.',
                    'ar' => 'أكمل أول وحدة تدريبية.',
                    'de' => 'Schließe dein erstes Trainingsmodul ab.',
                    'zh' => '完成你的第一个培训模块。',
                    'ru' => 'Заверши свой первый учебный модуль.',
                    'hi' => 'अपना पहला प्रशिक्षण मॉड्यूल पूरा करें।',
                ],
                'category' => 'training',
                'xp_reward' => 30,
                'criteria' => ['type' => 'training_count', 'count' => 1, 'rarity' => 'common'],
                'sort_order' => 105,
            ],
            [
                'slug' => 'telegram_linked',
                'names' => [
                    'en' => 'Telegram Pioneer',
                    'fr' => 'Pionnier Telegram',
                    'es' => 'Pionero Telegram',
                    'pt' => 'Pioneiro Telegram',
                    'ar' => 'رائد تيليجرام',
                    'de' => 'Telegram-Pionier',
                    'zh' => 'Telegram先锋',
                    'ru' => 'Пионер Telegram',
                    'hi' => 'Telegram अग्रदूत',
                ],
                'descriptions' => [
                    'en' => 'Link your Telegram account.',
                    'fr' => 'Lie ton compte Telegram.',
                    'es' => 'Vincula tu cuenta de Telegram.',
                    'pt' => 'Vincule sua conta do Telegram.',
                    'ar' => 'اربط حسابك على تيليجرام.',
                    'de' => 'Verknüpfe dein Telegram-Konto.',
                    'zh' => '关联你的Telegram账号。',
                    'ru' => 'Привяжи свой аккаунт Telegram.',
                    'hi' => 'अपना Telegram अकाउंट लिंक करें।',
                ],
                'category' => 'special',
                'xp_reward' => 50,
                'criteria' => ['type' => 'telegram_linked', 'rarity' => 'common'],
                'sort_order' => 106,
            ],
            [
                'slug' => 'zoom_first',
                'names' => [
                    'en' => 'First Zoom',
                    'fr' => 'Premier Zoom',
                    'es' => 'Primer Zoom',
                    'pt' => 'Primeiro Zoom',
                    'ar' => 'أول زووم',
                    'de' => 'Erstes Zoom',
                    'zh' => '首次Zoom',
                    'ru' => 'Первый Zoom',
                    'hi' => 'पहला Zoom',
                ],
                'descriptions' => [
                    'en' => 'Attend your first Zoom training session.',
                    'fr' => 'Participe à ta première session Zoom.',
                    'es' => 'Asiste a tu primera sesión de formación en Zoom.',
                    'pt' => 'Participe da sua primeira sessão de treinamento no Zoom.',
                    'ar' => 'احضر أول جلسة تدريب عبر زووم.',
                    'de' => 'Nimm an deiner ersten Zoom-Schulung teil.',
                    'zh' => '参加你的第一次Zoom培训课程。',
                    'ru' => 'Посети первую тренировку в Zoom.',
                    'hi' => 'अपने पहले Zoom प्रशिक्षण सत्र में भाग लें।',
                ],
                'category' => 'training',
                'xp_reward' => 40,
                'criteria' => ['type' => 'zoom_count', 'count' => 1, 'rarity' => 'common'],
                'sort_order' => 107,
            ],

            // ── Uncommon (7) ───────────────────────────────────────────
            [
                'slug' => 'clients_10',
                'names' => [
                    'en' => '10 Clients',
                    'fr' => '10 Clients',
                    'es' => '10 Clientes',
                    'pt' => '10 Clientes',
                    'ar' => '10 عملاء',
                    'de' => '10 Kunden',
                    'zh' => '10位客户',
                    'ru' => '10 клиентов',
                    'hi' => '10 ग्राहक',
                ],
                'descriptions' => [
                    'en' => 'Reach 10 total clients.',
                    'fr' => 'Atteins 10 clients au total.',
                    'es' => 'Alcanza 10 clientes en total.',
                    'pt' => 'Alcance 10 clientes no total.',
                    'ar' => 'احصل على 10 عملاء إجمالاً.',
                    'de' => 'Erreiche insgesamt 10 Kunden.',
                    'zh' => '累计获得10位客户。',
                    'ru' => 'Набери 10 клиентов в сумме.',
                    'hi' => 'कुल 10 ग्राहक तक पहुंचें।',
                ],
                'category' => 'sales',
                'xp_reward' => 150,
                'criteria' => ['type' => 'sales_count', 'count' => 10, 'rarity' => 'uncommon'],
                'sort_order' => 200,
            ],
            [
                'slug' => 'first_recruitment',
                'names' => [
                    'en' => 'Recruiter',
                    'fr' => 'Recruteur',
                    'es' => 'Reclutador',
                    'pt' => 'Recrutador',
                    'ar' => 'مجنّد',
                    'de' => 'Rekrutierer',
                    'zh' => '招募者',
                    'ru' => 'Рекрутер',
                    'hi' => 'भर्तीकर्ता',
                ],
                'descriptions' => [
                    'en' => 'Recruit your first chatter.',
                    'fr' => 'Recrute ton premier chatter.',
                    'es' => 'Recluta a tu primer chatter.',
                    'pt' => 'Recrute seu primeiro chatter.',
                    'ar' => 'قم بتجنيد أول chatter لك.',
                    'de' => 'Rekrutiere deinen ersten Chatter.',
                    'zh' => '招募你的第一个聊天员。',
                    'ru' => 'Набери своего первого чаттера.',
                    'hi' => 'अपना पहला चैटर भर्ती करें।',
                ],
                'category' => 'social',
                'xp_reward' => 100,
                'criteria' => ['type' => 'referral_count', 'count' => 1, 'rarity' => 'uncommon'],
                'sort_order' => 201,
            ],
            [
                'slug' => 'earned_100',
                'names' => [
                    'en' => '$100 Earned',
                    'fr' => '100$ Gagnés',
                    'es' => '$100 Ganados',
                    'pt' => '$100 Ganhos',
                    'ar' => '$100 مكتسبة',
                    'de' => '$100 Verdient',
                    'zh' => '赚取$100',
                    'ru' => '$100 заработано',
                    'hi' => '$100 कमाए',
                ],
                'descriptions' => [
                    'en' => 'Earn a total of $100 in commissions.',
                    'fr' => 'Gagne un total de 100$ en commissions.',
                    'es' => 'Gana un total de $100 en comisiones.',
                    'pt' => 'Ganhe um total de $100 em comissões.',
                    'ar' => 'اكسب ما مجموعه $100 من العمولات.',
                    'de' => 'Verdiene insgesamt $100 an Provisionen.',
                    'zh' => '累计赚取$100佣金。',
                    'ru' => 'Заработай $100 комиссионных.',
                    'hi' => 'कमीशन में कुल $100 कमाएं।',
                ],
                'category' => 'revenue',
                'xp_reward' => 100,
                'criteria' => ['type' => 'earnings_cents', 'count' => 10000, 'rarity' => 'uncommon'],
                'sort_order' => 202,
            ],
            [
                'slug' => 'multi_platform',
                'names' => [
                    'en' => 'Multi Platform',
                    'fr' => 'Multi Plateforme',
                    'es' => 'Multiplataforma',
                    'pt' => 'Multiplataforma',
                    'ar' => 'متعدد المنصات',
                    'de' => 'Multiplattform',
                    'zh' => '多平台',
                    'ru' => 'Мультиплатформа',
                    'hi' => 'मल्टी प्लेटफ़ॉर्म',
                ],
                'descriptions' => [
                    'en' => 'Share your link on multiple platforms.',
                    'fr' => 'Partage ton lien sur plusieurs plateformes.',
                    'es' => 'Comparte tu enlace en varias plataformas.',
                    'pt' => 'Compartilhe seu link em várias plataformas.',
                    'ar' => 'شارك رابطك على عدة منصات.',
                    'de' => 'Teile deinen Link auf mehreren Plattformen.',
                    'zh' => '在多个平台上分享你的链接。',
                    'ru' => 'Поделись ссылкой на нескольких платформах.',
                    'hi' => 'अपना लिंक कई प्लेटफ़ॉर्म पर शेयर करें।',
                ],
                'category' => 'special',
                'xp_reward' => 75,
                'criteria' => ['type' => 'multi_platform', 'rarity' => 'uncommon'],
                'sort_order' => 203,
            ],
            [
                'slug' => 'streak_14',
                'names' => [
                    'en' => '2-Week Champion',
                    'fr' => 'Champion de 2 Semaines',
                    'es' => 'Campeón de 2 Semanas',
                    'pt' => 'Campeão de 2 Semanas',
                    'ar' => 'بطل الأسبوعين',
                    'de' => '2-Wochen-Champion',
                    'zh' => '两周冠军',
                    'ru' => 'Чемпион 2 недель',
                    'hi' => '2 सप्ताह का चैंपियन',
                ],
                'descriptions' => [
                    'en' => 'Maintain a 14-day activity streak.',
                    'fr' => 'Maintiens une série d\'activité de 14 jours.',
                    'es' => 'Mantén una racha de actividad de 14 días.',
                    'pt' => 'Mantenha uma sequência de atividade de 14 dias.',
                    'ar' => 'حافظ على سلسلة نشاط لمدة 14 يوماً.',
                    'de' => 'Halte eine 14-Tage-Aktivitätsserie aufrecht.',
                    'zh' => '保持14天连续活跃记录。',
                    'ru' => 'Поддерживай серию активности 14 дней.',
                    'hi' => '14 दिन की गतिविधि श्रृंखला बनाए रखें।',
                ],
                'category' => 'streak',
                'xp_reward' => 150,
                'criteria' => ['type' => 'streak', 'count' => 14, 'rarity' => 'uncommon'],
                'sort_order' => 204,
            ],
            [
                'slug' => 'training_complete',
                'names' => [
                    'en' => 'Training Complete',
                    'fr' => 'Formation Complète',
                    'es' => 'Formación Completa',
                    'pt' => 'Treinamento Completo',
                    'ar' => 'تدريب مكتمل',
                    'de' => 'Training Abgeschlossen',
                    'zh' => '培训完成',
                    'ru' => 'Обучение завершено',
                    'hi' => 'प्रशिक्षण पूर्ण',
                ],
                'descriptions' => [
                    'en' => 'Complete all available training modules.',
                    'fr' => 'Termine tous les modules de formation disponibles.',
                    'es' => 'Completa todos los módulos de formación disponibles.',
                    'pt' => 'Complete todos os módulos de treinamento disponíveis.',
                    'ar' => 'أكمل جميع وحدات التدريب المتاحة.',
                    'de' => 'Schließe alle verfügbaren Trainingsmodule ab.',
                    'zh' => '完成所有可用的培训模块。',
                    'ru' => 'Заверши все доступные учебные модули.',
                    'hi' => 'सभी उपलब्ध प्रशिक्षण मॉड्यूल पूरे करें।',
                ],
                'category' => 'training',
                'xp_reward' => 100,
                'criteria' => ['type' => 'all_training_complete', 'rarity' => 'uncommon'],
                'sort_order' => 205,
            ],
            [
                'slug' => 'speed_runner',
                'names' => [
                    'en' => 'Speed Runner',
                    'fr' => 'Speed Runner',
                    'es' => 'Velocista',
                    'pt' => 'Velocista',
                    'ar' => 'عدّاء سريع',
                    'de' => 'Sprinter',
                    'zh' => '飞速达人',
                    'ru' => 'Спринтер',
                    'hi' => 'स्पीड रनर',
                ],
                'descriptions' => [
                    'en' => 'Make a sale within your first 48 hours.',
                    'fr' => 'Fais une vente dans tes 48 premières heures.',
                    'es' => 'Realiza una venta en tus primeras 48 horas.',
                    'pt' => 'Faça uma venda nas suas primeiras 48 horas.',
                    'ar' => 'قم ببيع خلال أول 48 ساعة.',
                    'de' => 'Mache einen Verkauf in deinen ersten 48 Stunden.',
                    'zh' => '在前48小时内完成一笔销售。',
                    'ru' => 'Соверши продажу в первые 48 часов.',
                    'hi' => 'अपने पहले 48 घंटों में एक बिक्री करें।',
                ],
                'category' => 'special',
                'xp_reward' => 100,
                'criteria' => ['type' => 'sales_first_48h', 'rarity' => 'uncommon'],
                'sort_order' => 206,
            ],

            // ── Rare (10) ─────────────────────────────────────────────
            [
                'slug' => 'streak_30',
                'names' => [
                    'en' => 'Monthly Master',
                    'fr' => 'Maître du Mois',
                    'es' => 'Maestro Mensual',
                    'pt' => 'Mestre Mensal',
                    'ar' => 'سيد الشهر',
                    'de' => 'Monatsmeister',
                    'zh' => '月度大师',
                    'ru' => 'Мастер месяца',
                    'hi' => 'मासिक मास्टर',
                ],
                'descriptions' => [
                    'en' => 'Maintain a 30-day activity streak.',
                    'fr' => 'Maintiens une série d\'activité de 30 jours.',
                    'es' => 'Mantén una racha de actividad de 30 días.',
                    'pt' => 'Mantenha uma sequência de atividade de 30 dias.',
                    'ar' => 'حافظ على سلسلة نشاط لمدة 30 يوماً.',
                    'de' => 'Halte eine 30-Tage-Aktivitätsserie aufrecht.',
                    'zh' => '保持30天连续活跃记录。',
                    'ru' => 'Поддерживай серию активности 30 дней.',
                    'hi' => '30 दिन की गतिविधि श्रृंखला बनाए रखें।',
                ],
                'category' => 'streak',
                'xp_reward' => 300,
                'criteria' => ['type' => 'streak', 'count' => 30, 'rarity' => 'rare'],
                'sort_order' => 300,
            ],
            [
                'slug' => 'clients_50',
                'names' => [
                    'en' => '50 Clients',
                    'fr' => '50 Clients',
                    'es' => '50 Clientes',
                    'pt' => '50 Clientes',
                    'ar' => '50 عميل',
                    'de' => '50 Kunden',
                    'zh' => '50位客户',
                    'ru' => '50 клиентов',
                    'hi' => '50 ग्राहक',
                ],
                'descriptions' => [
                    'en' => 'Reach 50 total clients.',
                    'fr' => 'Atteins 50 clients au total.',
                    'es' => 'Alcanza 50 clientes en total.',
                    'pt' => 'Alcance 50 clientes no total.',
                    'ar' => 'احصل على 50 عميل إجمالاً.',
                    'de' => 'Erreiche insgesamt 50 Kunden.',
                    'zh' => '累计获得50位客户。',
                    'ru' => 'Набери 50 клиентов в сумме.',
                    'hi' => 'कुल 50 ग्राहक तक पहुंचें।',
                ],
                'category' => 'sales',
                'xp_reward' => 300,
                'criteria' => ['type' => 'sales_count', 'count' => 50, 'rarity' => 'rare'],
                'sort_order' => 301,
            ],
            [
                'slug' => 'recruits_3',
                'names' => [
                    'en' => 'Team Builder',
                    'fr' => 'Bâtisseur d\'Équipe',
                    'es' => 'Constructor de Equipo',
                    'pt' => 'Construtor de Equipe',
                    'ar' => 'بانٍ للفريق',
                    'de' => 'Teambuilder',
                    'zh' => '团队建造者',
                    'ru' => 'Строитель команды',
                    'hi' => 'टीम बिल्डर',
                ],
                'descriptions' => [
                    'en' => 'Recruit 3 chatters to your team.',
                    'fr' => 'Recrute 3 chatters dans ton équipe.',
                    'es' => 'Recluta 3 chatters para tu equipo.',
                    'pt' => 'Recrute 3 chatters para sua equipe.',
                    'ar' => 'جنّد 3 chatters لفريقك.',
                    'de' => 'Rekrutiere 3 Chatter für dein Team.',
                    'zh' => '为你的团队招募3名聊天员。',
                    'ru' => 'Набери 3 чаттеров в свою команду.',
                    'hi' => 'अपनी टीम में 3 चैटर भर्ती करें।',
                ],
                'category' => 'social',
                'xp_reward' => 200,
                'criteria' => ['type' => 'referral_count', 'count' => 3, 'rarity' => 'rare'],
                'sort_order' => 302,
            ],
            [
                'slug' => 'recruits_5',
                'names' => [
                    'en' => 'Squad Leader',
                    'fr' => 'Chef d\'Escouade',
                    'es' => 'Líder de Escuadrón',
                    'pt' => 'Líder de Esquadrão',
                    'ar' => 'قائد الفرقة',
                    'de' => 'Truppführer',
                    'zh' => '小队队长',
                    'ru' => 'Командир отряда',
                    'hi' => 'दस्ते का नेता',
                ],
                'descriptions' => [
                    'en' => 'Recruit 5 chatters to your team.',
                    'fr' => 'Recrute 5 chatters dans ton équipe.',
                    'es' => 'Recluta 5 chatters para tu equipo.',
                    'pt' => 'Recrute 5 chatters para sua equipe.',
                    'ar' => 'جنّد 5 chatters لفريقك.',
                    'de' => 'Rekrutiere 5 Chatter für dein Team.',
                    'zh' => '为你的团队招募5名聊天员。',
                    'ru' => 'Набери 5 чаттеров в свою команду.',
                    'hi' => 'अपनी टीम में 5 चैटर भर्ती करें।',
                ],
                'category' => 'social',
                'xp_reward' => 250,
                'criteria' => ['type' => 'referral_count', 'count' => 5, 'rarity' => 'rare'],
                'sort_order' => 303,
            ],
            [
                'slug' => 'earned_500',
                'names' => [
                    'en' => '$500 Earned',
                    'fr' => '500$ Gagnés',
                    'es' => '$500 Ganados',
                    'pt' => '$500 Ganhos',
                    'ar' => '$500 مكتسبة',
                    'de' => '$500 Verdient',
                    'zh' => '赚取$500',
                    'ru' => '$500 заработано',
                    'hi' => '$500 कमाए',
                ],
                'descriptions' => [
                    'en' => 'Earn a total of $500 in commissions.',
                    'fr' => 'Gagne un total de 500$ en commissions.',
                    'es' => 'Gana un total de $500 en comisiones.',
                    'pt' => 'Ganhe um total de $500 em comissões.',
                    'ar' => 'اكسب ما مجموعه $500 من العمولات.',
                    'de' => 'Verdiene insgesamt $500 an Provisionen.',
                    'zh' => '累计赚取$500佣金。',
                    'ru' => 'Заработай $500 комиссионных.',
                    'hi' => 'कमीशन में कुल $500 कमाएं।',
                ],
                'category' => 'revenue',
                'xp_reward' => 250,
                'criteria' => ['type' => 'earnings_cents', 'count' => 50000, 'rarity' => 'rare'],
                'sort_order' => 304,
            ],
            [
                'slug' => 'level_3',
                'names' => [
                    'en' => 'Active',
                    'fr' => 'Actif',
                    'es' => 'Activo',
                    'pt' => 'Ativo',
                    'ar' => 'نشط',
                    'de' => 'Aktiv',
                    'zh' => '活跃',
                    'ru' => 'Активный',
                    'hi' => 'सक्रिय',
                ],
                'descriptions' => [
                    'en' => 'Reach level 3.',
                    'fr' => 'Atteins le niveau 3.',
                    'es' => 'Alcanza el nivel 3.',
                    'pt' => 'Alcance o nível 3.',
                    'ar' => 'ابلغ المستوى 3.',
                    'de' => 'Erreiche Level 3.',
                    'zh' => '达到等级3。',
                    'ru' => 'Достигни уровня 3.',
                    'hi' => 'लेवल 3 तक पहुंचें।',
                ],
                'category' => 'level',
                'xp_reward' => 150,
                'criteria' => ['type' => 'level', 'count' => 3, 'rarity' => 'rare'],
                'sort_order' => 305,
            ],
            [
                'slug' => 'top3_monthly',
                'names' => [
                    'en' => 'Top 3 Monthly',
                    'fr' => 'Top 3 Mensuel',
                    'es' => 'Top 3 Mensual',
                    'pt' => 'Top 3 Mensal',
                    'ar' => 'أفضل 3 شهرياً',
                    'de' => 'Top 3 Monatlich',
                    'zh' => '月度前三',
                    'ru' => 'Топ-3 месяца',
                    'hi' => 'मासिक टॉप 3',
                ],
                'descriptions' => [
                    'en' => 'Finish in the top 3 of the monthly leaderboard.',
                    'fr' => 'Termine dans le top 3 du classement mensuel.',
                    'es' => 'Termina en el top 3 del ranking mensual.',
                    'pt' => 'Termine entre os 3 primeiros do ranking mensal.',
                    'ar' => 'انهِ في المراكز الثلاثة الأولى من الترتيب الشهري.',
                    'de' => 'Beende den Monat in den Top 3 der Rangliste.',
                    'zh' => '在月度排行榜中进入前三名。',
                    'ru' => 'Попади в топ-3 месячного рейтинга.',
                    'hi' => 'मासिक लीडरबोर्ड में टॉप 3 में रहें।',
                ],
                'category' => 'leaderboard',
                'xp_reward' => 300,
                'criteria' => ['type' => 'leaderboard_monthly_top', 'count' => 3, 'rarity' => 'rare'],
                'sort_order' => 306,
            ],
            [
                'slug' => 'team_10',
                'names' => [
                    'en' => 'Team of 10',
                    'fr' => 'Équipe de 10',
                    'es' => 'Equipo de 10',
                    'pt' => 'Equipe de 10',
                    'ar' => 'فريق من 10',
                    'de' => 'Team von 10',
                    'zh' => '10人团队',
                    'ru' => 'Команда из 10',
                    'hi' => '10 की टीम',
                ],
                'descriptions' => [
                    'en' => 'Build a team of 10 active members.',
                    'fr' => 'Construis une équipe de 10 membres actifs.',
                    'es' => 'Construye un equipo de 10 miembros activos.',
                    'pt' => 'Monte uma equipe de 10 membros ativos.',
                    'ar' => 'ابنِ فريقاً من 10 أعضاء نشطين.',
                    'de' => 'Baue ein Team von 10 aktiven Mitgliedern auf.',
                    'zh' => '组建一支10名活跃成员的团队。',
                    'ru' => 'Собери команду из 10 активных участников.',
                    'hi' => '10 सक्रिय सदस्यों की टीम बनाएं।',
                ],
                'category' => 'social',
                'xp_reward' => 200,
                'criteria' => ['type' => 'team_size', 'count' => 10, 'rarity' => 'rare'],
                'sort_order' => 307,
            ],
            [
                'slug' => 'night_owl',
                'names' => [
                    'en' => 'Night Owl',
                    'fr' => 'Noctambule',
                    'es' => 'Búho Nocturno',
                    'pt' => 'Coruja Noturna',
                    'ar' => 'بومة الليل',
                    'de' => 'Nachteule',
                    'zh' => '夜猫子',
                    'ru' => 'Полуночник',
                    'hi' => 'रात का उल्लू',
                ],
                'descriptions' => [
                    'en' => 'Make a sale between midnight and 5 AM.',
                    'fr' => 'Fais une vente entre minuit et 5h du matin.',
                    'es' => 'Realiza una venta entre medianoche y las 5 AM.',
                    'pt' => 'Faça uma venda entre meia-noite e 5h da manhã.',
                    'ar' => 'قم ببيع بين منتصف الليل و5 صباحاً.',
                    'de' => 'Mache einen Verkauf zwischen Mitternacht und 5 Uhr morgens.',
                    'zh' => '在午夜到凌晨5点之间完成一笔销售。',
                    'ru' => 'Соверши продажу между полуночью и 5 утра.',
                    'hi' => 'आधी रात से सुबह 5 बजे के बीच एक बिक्री करें।',
                ],
                'category' => 'special',
                'xp_reward' => 100,
                'criteria' => ['type' => 'night_sale', 'rarity' => 'rare'],
                'sort_order' => 308,
            ],
            [
                'slug' => 'comeback_king',
                'names' => [
                    'en' => 'Comeback King',
                    'fr' => 'Roi du Comeback',
                    'es' => 'Rey del Regreso',
                    'pt' => 'Rei da Volta',
                    'ar' => 'ملك العودة',
                    'de' => 'Comeback-König',
                    'zh' => '回归之王',
                    'ru' => 'Король камбэка',
                    'hi' => 'कमबैक किंग',
                ],
                'descriptions' => [
                    'en' => 'Return and make a sale after 30 days of inactivity.',
                    'fr' => 'Reviens et fais une vente après 30 jours d\'inactivité.',
                    'es' => 'Regresa y realiza una venta tras 30 días de inactividad.',
                    'pt' => 'Volte e faça uma venda após 30 dias de inatividade.',
                    'ar' => 'عد وقم ببيع بعد 30 يوم من عدم النشاط.',
                    'de' => 'Kehre zurück und mache einen Verkauf nach 30 Tagen Inaktivität.',
                    'zh' => '在30天不活跃后回归并完成一笔销售。',
                    'ru' => 'Вернись и соверши продажу после 30 дней неактивности.',
                    'hi' => '30 दिन की निष्क्रियता के बाद लौटें और बिक्री करें।',
                ],
                'category' => 'special',
                'xp_reward' => 200,
                'criteria' => ['type' => 'comeback_after_30d', 'rarity' => 'rare'],
                'sort_order' => 309,
            ],

            // ── Epic (11) ─────────────────────────────────────────────
            [
                'slug' => 'streak_100',
                'names' => [
                    'en' => 'Century Streak',
                    'fr' => 'Série Centenaire',
                    'es' => 'Racha Centenaria',
                    'pt' => 'Sequência Centenária',
                    'ar' => 'سلسلة المئة',
                    'de' => 'Jahrhundertserie',
                    'zh' => '百日连胜',
                    'ru' => 'Столетняя серия',
                    'hi' => 'शतक श्रृंखला',
                ],
                'descriptions' => [
                    'en' => 'Maintain a 100-day activity streak.',
                    'fr' => 'Maintiens une série d\'activité de 100 jours.',
                    'es' => 'Mantén una racha de actividad de 100 días.',
                    'pt' => 'Mantenha uma sequência de atividade de 100 dias.',
                    'ar' => 'حافظ على سلسلة نشاط لمدة 100 يوم.',
                    'de' => 'Halte eine 100-Tage-Aktivitätsserie aufrecht.',
                    'zh' => '保持100天连续活跃记录。',
                    'ru' => 'Поддерживай серию активности 100 дней.',
                    'hi' => '100 दिन की गतिविधि श्रृंखला बनाए रखें।',
                ],
                'category' => 'streak',
                'xp_reward' => 500,
                'criteria' => ['type' => 'streak', 'count' => 100, 'rarity' => 'epic'],
                'sort_order' => 400,
            ],
            [
                'slug' => 'clients_100',
                'names' => [
                    'en' => 'Century Club',
                    'fr' => 'Club des 100',
                    'es' => 'Club de los 100',
                    'pt' => 'Clube dos 100',
                    'ar' => 'نادي المئة',
                    'de' => 'Club der 100',
                    'zh' => '百人俱乐部',
                    'ru' => 'Клуб сотни',
                    'hi' => 'सेंचुरी क्लब',
                ],
                'descriptions' => [
                    'en' => 'Reach 100 total clients.',
                    'fr' => 'Atteins 100 clients au total.',
                    'es' => 'Alcanza 100 clientes en total.',
                    'pt' => 'Alcance 100 clientes no total.',
                    'ar' => 'احصل على 100 عميل إجمالاً.',
                    'de' => 'Erreiche insgesamt 100 Kunden.',
                    'zh' => '累计获得100位客户。',
                    'ru' => 'Набери 100 клиентов в сумме.',
                    'hi' => 'कुल 100 ग्राहक तक पहुंचें।',
                ],
                'category' => 'sales',
                'xp_reward' => 500,
                'criteria' => ['type' => 'sales_count', 'count' => 100, 'rarity' => 'epic'],
                'sort_order' => 401,
            ],
            [
                'slug' => 'recruits_10',
                'names' => [
                    'en' => 'Commander',
                    'fr' => 'Commandant',
                    'es' => 'Comandante',
                    'pt' => 'Comandante',
                    'ar' => 'قائد',
                    'de' => 'Kommandant',
                    'zh' => '指挥官',
                    'ru' => 'Командир',
                    'hi' => 'कमांडर',
                ],
                'descriptions' => [
                    'en' => 'Recruit 10 chatters to your team.',
                    'fr' => 'Recrute 10 chatters dans ton équipe.',
                    'es' => 'Recluta 10 chatters para tu equipo.',
                    'pt' => 'Recrute 10 chatters para sua equipe.',
                    'ar' => 'جنّد 10 chatters لفريقك.',
                    'de' => 'Rekrutiere 10 Chatter für dein Team.',
                    'zh' => '为你的团队招募10名聊天员。',
                    'ru' => 'Набери 10 чаттеров в свою команду.',
                    'hi' => 'अपनी टीम में 10 चैटर भर्ती करें।',
                ],
                'category' => 'social',
                'xp_reward' => 400,
                'criteria' => ['type' => 'referral_count', 'count' => 10, 'rarity' => 'epic'],
                'sort_order' => 402,
            ],
            [
                'slug' => 'recruits_25',
                'names' => [
                    'en' => 'General',
                    'fr' => 'Général',
                    'es' => 'General',
                    'pt' => 'General',
                    'ar' => 'جنرال',
                    'de' => 'General',
                    'zh' => '将军',
                    'ru' => 'Генерал',
                    'hi' => 'जनरल',
                ],
                'descriptions' => [
                    'en' => 'Recruit 25 chatters to your team.',
                    'fr' => 'Recrute 25 chatters dans ton équipe.',
                    'es' => 'Recluta 25 chatters para tu equipo.',
                    'pt' => 'Recrute 25 chatters para sua equipe.',
                    'ar' => 'جنّد 25 chatter لفريقك.',
                    'de' => 'Rekrutiere 25 Chatter für dein Team.',
                    'zh' => '为你的团队招募25名聊天员。',
                    'ru' => 'Набери 25 чаттеров в свою команду.',
                    'hi' => 'अपनी टीम में 25 चैटर भर्ती करें।',
                ],
                'category' => 'social',
                'xp_reward' => 500,
                'criteria' => ['type' => 'referral_count', 'count' => 25, 'rarity' => 'epic'],
                'sort_order' => 403,
            ],
            [
                'slug' => 'earned_1000',
                'names' => [
                    'en' => '$1000 Earned',
                    'fr' => '1000$ Gagnés',
                    'es' => '$1000 Ganados',
                    'pt' => '$1000 Ganhos',
                    'ar' => '$1000 مكتسبة',
                    'de' => '$1000 Verdient',
                    'zh' => '赚取$1000',
                    'ru' => '$1000 заработано',
                    'hi' => '$1000 कमाए',
                ],
                'descriptions' => [
                    'en' => 'Earn a total of $1,000 in commissions.',
                    'fr' => 'Gagne un total de 1000$ en commissions.',
                    'es' => 'Gana un total de $1,000 en comisiones.',
                    'pt' => 'Ganhe um total de $1,000 em comissões.',
                    'ar' => 'اكسب ما مجموعه $1,000 من العمولات.',
                    'de' => 'Verdiene insgesamt $1.000 an Provisionen.',
                    'zh' => '累计赚取$1,000佣金。',
                    'ru' => 'Заработай $1,000 комиссионных.',
                    'hi' => 'कमीशन में कुल $1,000 कमाएं।',
                ],
                'category' => 'revenue',
                'xp_reward' => 500,
                'criteria' => ['type' => 'earnings_cents', 'count' => 100000, 'rarity' => 'epic'],
                'sort_order' => 404,
            ],
            [
                'slug' => 'level_4',
                'names' => [
                    'en' => 'Ambassador',
                    'fr' => 'Ambassadeur',
                    'es' => 'Embajador',
                    'pt' => 'Embaixador',
                    'ar' => 'سفير',
                    'de' => 'Botschafter',
                    'zh' => '大使',
                    'ru' => 'Посол',
                    'hi' => 'राजदूत',
                ],
                'descriptions' => [
                    'en' => 'Reach level 4.',
                    'fr' => 'Atteins le niveau 4.',
                    'es' => 'Alcanza el nivel 4.',
                    'pt' => 'Alcance o nível 4.',
                    'ar' => 'ابلغ المستوى 4.',
                    'de' => 'Erreiche Level 4.',
                    'zh' => '达到等级4。',
                    'ru' => 'Достигни уровня 4.',
                    'hi' => 'लेवल 4 तक पहुंचें।',
                ],
                'category' => 'level',
                'xp_reward' => 300,
                'criteria' => ['type' => 'level', 'count' => 4, 'rarity' => 'epic'],
                'sort_order' => 405,
            ],
            [
                'slug' => 'team_25',
                'names' => [
                    'en' => 'Team of 25',
                    'fr' => 'Équipe de 25',
                    'es' => 'Equipo de 25',
                    'pt' => 'Equipe de 25',
                    'ar' => 'فريق من 25',
                    'de' => 'Team von 25',
                    'zh' => '25人团队',
                    'ru' => 'Команда из 25',
                    'hi' => '25 की टीम',
                ],
                'descriptions' => [
                    'en' => 'Build a team of 25 active members.',
                    'fr' => 'Construis une équipe de 25 membres actifs.',
                    'es' => 'Construye un equipo de 25 miembros activos.',
                    'pt' => 'Monte uma equipe de 25 membros ativos.',
                    'ar' => 'ابنِ فريقاً من 25 عضواً نشطاً.',
                    'de' => 'Baue ein Team von 25 aktiven Mitgliedern auf.',
                    'zh' => '组建一支25名活跃成员的团队。',
                    'ru' => 'Собери команду из 25 активных участников.',
                    'hi' => '25 सक्रिय सदस्यों की टीम बनाएं।',
                ],
                'category' => 'social',
                'xp_reward' => 400,
                'criteria' => ['type' => 'team_size', 'count' => 25, 'rarity' => 'epic'],
                'sort_order' => 406,
            ],
            [
                'slug' => 'team_50',
                'names' => [
                    'en' => 'Team of 50',
                    'fr' => 'Équipe de 50',
                    'es' => 'Equipo de 50',
                    'pt' => 'Equipe de 50',
                    'ar' => 'فريق من 50',
                    'de' => 'Team von 50',
                    'zh' => '50人团队',
                    'ru' => 'Команда из 50',
                    'hi' => '50 की टीम',
                ],
                'descriptions' => [
                    'en' => 'Build a team of 50 active members.',
                    'fr' => 'Construis une équipe de 50 membres actifs.',
                    'es' => 'Construye un equipo de 50 miembros activos.',
                    'pt' => 'Monte uma equipe de 50 membros ativos.',
                    'ar' => 'ابنِ فريقاً من 50 عضواً نشطاً.',
                    'de' => 'Baue ein Team von 50 aktiven Mitgliedern auf.',
                    'zh' => '组建一支50名活跃成员的团队。',
                    'ru' => 'Собери команду из 50 активных участников.',
                    'hi' => '50 सक्रिय सदस्यों की टीम बनाएं।',
                ],
                'category' => 'social',
                'xp_reward' => 500,
                'criteria' => ['type' => 'team_size', 'count' => 50, 'rarity' => 'epic'],
                'sort_order' => 407,
            ],
            [
                'slug' => 'team_earned_1000',
                'names' => [
                    'en' => 'Team $1000',
                    'fr' => 'Équipe 1000$',
                    'es' => 'Equipo $1000',
                    'pt' => 'Equipe $1000',
                    'ar' => 'فريق $1000',
                    'de' => 'Team $1000',
                    'zh' => '团队$1000',
                    'ru' => 'Команда $1000',
                    'hi' => 'टीम $1000',
                ],
                'descriptions' => [
                    'en' => 'Your team earns a combined total of $1,000.',
                    'fr' => 'Ton équipe gagne un total combiné de 1000$.',
                    'es' => 'Tu equipo gana un total combinado de $1,000.',
                    'pt' => 'Sua equipe ganha um total combinado de $1,000.',
                    'ar' => 'يكسب فريقك مجموعاً قدره $1,000.',
                    'de' => 'Dein Team verdient zusammen insgesamt $1.000.',
                    'zh' => '你的团队累计赚取$1,000。',
                    'ru' => 'Твоя команда зарабатывает в сумме $1,000.',
                    'hi' => 'आपकी टीम कुल मिलाकर $1,000 कमाए।',
                ],
                'category' => 'social',
                'xp_reward' => 500,
                'criteria' => ['type' => 'team_earnings_cents', 'count' => 100000, 'rarity' => 'epic'],
                'sort_order' => 408,
            ],
            [
                'slug' => 'pentakill',
                'names' => [
                    'en' => 'Pentakill',
                    'fr' => 'Pentakill',
                    'es' => 'Pentakill',
                    'pt' => 'Pentakill',
                    'ar' => 'بنتاكيل',
                    'de' => 'Pentakill',
                    'zh' => '五杀',
                    'ru' => 'Пентакилл',
                    'hi' => 'पेंटाकिल',
                ],
                'descriptions' => [
                    'en' => 'Make 5 sales in a single day.',
                    'fr' => 'Fais 5 ventes en une seule journée.',
                    'es' => 'Realiza 5 ventas en un solo día.',
                    'pt' => 'Faça 5 vendas em um único dia.',
                    'ar' => 'قم بـ5 مبيعات في يوم واحد.',
                    'de' => 'Mache 5 Verkäufe an einem einzigen Tag.',
                    'zh' => '在一天内完成5笔销售。',
                    'ru' => 'Соверши 5 продаж за один день.',
                    'hi' => 'एक ही दिन में 5 बिक्री करें।',
                ],
                'category' => 'special',
                'xp_reward' => 500,
                'criteria' => ['type' => '5_sales_1_day', 'rarity' => 'epic'],
                'sort_order' => 409,
            ],
            [
                'slug' => 'golden_mentor',
                'names' => [
                    'en' => 'Golden Mentor',
                    'fr' => 'Mentor d\'Or',
                    'es' => 'Mentor de Oro',
                    'pt' => 'Mentor de Ouro',
                    'ar' => 'المرشد الذهبي',
                    'de' => 'Goldener Mentor',
                    'zh' => '金牌导师',
                    'ru' => 'Золотой наставник',
                    'hi' => 'गोल्डन मेंटर',
                ],
                'descriptions' => [
                    'en' => 'One of your recruits earns $500.',
                    'fr' => 'Un de tes filleuls gagne 500$.',
                    'es' => 'Uno de tus reclutas gana $500.',
                    'pt' => 'Um de seus recrutados ganha $500.',
                    'ar' => 'أحد المجنّدين لديك يكسب $500.',
                    'de' => 'Einer deiner Rekruten verdient $500.',
                    'zh' => '你招募的一位成员赚取$500。',
                    'ru' => 'Один из твоих рекрутов зарабатывает $500.',
                    'hi' => 'आपके एक भर्ती किए गए व्यक्ति ने $500 कमाए।',
                ],
                'category' => 'social',
                'xp_reward' => 500,
                'criteria' => ['type' => 'referral_earned_500', 'rarity' => 'epic'],
                'sort_order' => 410,
            ],

            // ── Legendary (8) ─────────────────────────────────────────
            [
                'slug' => 'top1_monthly',
                'names' => [
                    'en' => 'Monthly Champion',
                    'fr' => 'Champion du Mois',
                    'es' => 'Campeón del Mes',
                    'pt' => 'Campeão do Mês',
                    'ar' => 'بطل الشهر',
                    'de' => 'Monatschampion',
                    'zh' => '月度冠军',
                    'ru' => 'Чемпион месяца',
                    'hi' => 'मासिक चैंपियन',
                ],
                'descriptions' => [
                    'en' => 'Finish #1 on the monthly leaderboard.',
                    'fr' => 'Termine #1 au classement mensuel.',
                    'es' => 'Termina #1 en el ranking mensual.',
                    'pt' => 'Termine em #1 no ranking mensal.',
                    'ar' => 'انهِ في المرتبة الأولى بالترتيب الشهري.',
                    'de' => 'Beende den Monat als #1 der Rangliste.',
                    'zh' => '在月度排行榜中获得第一名。',
                    'ru' => 'Займи 1-е место в месячном рейтинге.',
                    'hi' => 'मासिक लीडरबोर्ड में #1 पर रहें।',
                ],
                'category' => 'leaderboard',
                'xp_reward' => 1000,
                'criteria' => ['type' => 'leaderboard_monthly_top', 'count' => 1, 'rarity' => 'legendary'],
                'sort_order' => 500,
            ],
            [
                'slug' => 'level_5',
                'names' => [
                    'en' => 'Legend',
                    'fr' => 'Légende',
                    'es' => 'Leyenda',
                    'pt' => 'Lenda',
                    'ar' => 'أسطورة',
                    'de' => 'Legende',
                    'zh' => '传奇',
                    'ru' => 'Легенда',
                    'hi' => 'लेजेंड',
                ],
                'descriptions' => [
                    'en' => 'Reach level 5 — the highest tier.',
                    'fr' => 'Atteins le niveau 5 — le rang ultime.',
                    'es' => 'Alcanza el nivel 5 — el rango más alto.',
                    'pt' => 'Alcance o nível 5 — o maior patamar.',
                    'ar' => 'ابلغ المستوى 5 — أعلى رتبة.',
                    'de' => 'Erreiche Level 5 — die höchste Stufe.',
                    'zh' => '达到等级5——最高级别。',
                    'ru' => 'Достигни уровня 5 — наивысшего ранга.',
                    'hi' => 'लेवल 5 तक पहुंचें — सबसे ऊंचा स्तर।',
                ],
                'category' => 'level',
                'xp_reward' => 500,
                'criteria' => ['type' => 'level', 'count' => 5, 'rarity' => 'legendary'],
                'sort_order' => 501,
            ],
            [
                'slug' => 'recruits_50',
                'names' => [
                    'en' => 'Army Builder',
                    'fr' => 'Bâtisseur d\'Armée',
                    'es' => 'Constructor de Ejército',
                    'pt' => 'Construtor de Exército',
                    'ar' => 'بانٍ للجيش',
                    'de' => 'Armeeaufbauer',
                    'zh' => '军队建造者',
                    'ru' => 'Строитель армии',
                    'hi' => 'सेना निर्माता',
                ],
                'descriptions' => [
                    'en' => 'Recruit 50 chatters to your team.',
                    'fr' => 'Recrute 50 chatters dans ton équipe.',
                    'es' => 'Recluta 50 chatters para tu equipo.',
                    'pt' => 'Recrute 50 chatters para sua equipe.',
                    'ar' => 'جنّد 50 chatter لفريقك.',
                    'de' => 'Rekrutiere 50 Chatter für dein Team.',
                    'zh' => '为你的团队招募50名聊天员。',
                    'ru' => 'Набери 50 чаттеров в свою команду.',
                    'hi' => 'अपनी टीम में 50 चैटर भर्ती करें।',
                ],
                'category' => 'social',
                'xp_reward' => 1000,
                'criteria' => ['type' => 'referral_count', 'count' => 50, 'rarity' => 'legendary'],
                'sort_order' => 502,
            ],
            [
                'slug' => 'team_100',
                'names' => [
                    'en' => 'Team of 100',
                    'fr' => 'Équipe de 100',
                    'es' => 'Equipo de 100',
                    'pt' => 'Equipe de 100',
                    'ar' => 'فريق من 100',
                    'de' => 'Team von 100',
                    'zh' => '100人团队',
                    'ru' => 'Команда из 100',
                    'hi' => '100 की टीम',
                ],
                'descriptions' => [
                    'en' => 'Build a team of 100 active members.',
                    'fr' => 'Construis une équipe de 100 membres actifs.',
                    'es' => 'Construye un equipo de 100 miembros activos.',
                    'pt' => 'Monte uma equipe de 100 membros ativos.',
                    'ar' => 'ابنِ فريقاً من 100 عضو نشط.',
                    'de' => 'Baue ein Team von 100 aktiven Mitgliedern auf.',
                    'zh' => '组建一支100名活跃成员的团队。',
                    'ru' => 'Собери команду из 100 активных участников.',
                    'hi' => '100 सक्रिय सदस्यों की टीम बनाएं।',
                ],
                'category' => 'social',
                'xp_reward' => 1000,
                'criteria' => ['type' => 'team_size', 'count' => 100, 'rarity' => 'legendary'],
                'sort_order' => 503,
            ],
            [
                'slug' => 'team_earned_5000',
                'names' => [
                    'en' => 'Team $5000',
                    'fr' => 'Équipe 5000$',
                    'es' => 'Equipo $5000',
                    'pt' => 'Equipe $5000',
                    'ar' => 'فريق $5000',
                    'de' => 'Team $5000',
                    'zh' => '团队$5000',
                    'ru' => 'Команда $5000',
                    'hi' => 'टीम $5000',
                ],
                'descriptions' => [
                    'en' => 'Your team earns a combined total of $5,000.',
                    'fr' => 'Ton équipe gagne un total combiné de 5000$.',
                    'es' => 'Tu equipo gana un total combinado de $5,000.',
                    'pt' => 'Sua equipe ganha um total combinado de $5,000.',
                    'ar' => 'يكسب فريقك مجموعاً قدره $5,000.',
                    'de' => 'Dein Team verdient zusammen insgesamt $5.000.',
                    'zh' => '你的团队累计赚取$5,000。',
                    'ru' => 'Твоя команда зарабатывает в сумме $5,000.',
                    'hi' => 'आपकी टीम कुल मिलाकर $5,000 कमाए।',
                ],
                'category' => 'social',
                'xp_reward' => 1000,
                'criteria' => ['type' => 'team_earnings_cents', 'count' => 500000, 'rarity' => 'legendary'],
                'sort_order' => 504,
            ],
            [
                'slug' => 'lightning_start',
                'names' => [
                    'en' => 'Lightning Start',
                    'fr' => 'Départ Éclair',
                    'es' => 'Inicio Relámpago',
                    'pt' => 'Início Relâmpago',
                    'ar' => 'بداية البرق',
                    'de' => 'Blitzstart',
                    'zh' => '闪电起步',
                    'ru' => 'Молниеносный старт',
                    'hi' => 'बिजली की शुरुआत',
                ],
                'descriptions' => [
                    'en' => 'Make 3 sales within your first 24 hours.',
                    'fr' => 'Fais 3 ventes dans tes 24 premières heures.',
                    'es' => 'Realiza 3 ventas en tus primeras 24 horas.',
                    'pt' => 'Faça 3 vendas nas suas primeiras 24 horas.',
                    'ar' => 'قم بـ3 مبيعات خلال أول 24 ساعة.',
                    'de' => 'Mache 3 Verkäufe in deinen ersten 24 Stunden.',
                    'zh' => '在前24小时内完成3笔销售。',
                    'ru' => 'Соверши 3 продажи в первые 24 часа.',
                    'hi' => 'अपने पहले 24 घंटों में 3 बिक्री करें।',
                ],
                'category' => 'special',
                'xp_reward' => 500,
                'criteria' => ['type' => '3_sales_first_day', 'rarity' => 'legendary'],
                'sort_order' => 505,
            ],
            [
                'slug' => 'perfectionist',
                'names' => [
                    'en' => 'Perfectionist',
                    'fr' => 'Perfectionniste',
                    'es' => 'Perfeccionista',
                    'pt' => 'Perfeccionista',
                    'ar' => 'مثالي',
                    'de' => 'Perfektionist',
                    'zh' => '完美主义者',
                    'ru' => 'Перфекционист',
                    'hi' => 'पूर्णतावादी',
                ],
                'descriptions' => [
                    'en' => 'Complete all daily missions for 7 consecutive days.',
                    'fr' => 'Termine toutes les missions quotidiennes pendant 7 jours consécutifs.',
                    'es' => 'Completa todas las misiones diarias durante 7 días consecutivos.',
                    'pt' => 'Complete todas as missões diárias por 7 dias consecutivos.',
                    'ar' => 'أكمل جميع المهام اليومية لمدة 7 أيام متتالية.',
                    'de' => 'Schließe alle täglichen Missionen 7 Tage in Folge ab.',
                    'zh' => '连续7天完成所有每日任务。',
                    'ru' => 'Выполняй все ежедневные миссии 7 дней подряд.',
                    'hi' => 'लगातार 7 दिन सभी दैनिक मिशन पूरे करें।',
                ],
                'category' => 'special',
                'xp_reward' => 1000,
                'criteria' => ['type' => 'all_daily_missions_7d', 'rarity' => 'legendary'],
                'sort_order' => 506,
            ],
            [
                'slug' => 'streak_365',
                'names' => [
                    'en' => 'Year of Fire',
                    'fr' => 'Année de Feu',
                    'es' => 'Año de Fuego',
                    'pt' => 'Ano de Fogo',
                    'ar' => 'عام النار',
                    'de' => 'Jahr des Feuers',
                    'zh' => '烈火之年',
                    'ru' => 'Год огня',
                    'hi' => 'आग का साल',
                ],
                'descriptions' => [
                    'en' => 'Maintain a 365-day activity streak. Absolute dedication.',
                    'fr' => 'Maintiens une série d\'activité de 365 jours. Dévouement absolu.',
                    'es' => 'Mantén una racha de actividad de 365 días. Dedicación absoluta.',
                    'pt' => 'Mantenha uma sequência de atividade de 365 dias. Dedicação absoluta.',
                    'ar' => 'حافظ على سلسلة نشاط لمدة 365 يوماً. تفانٍ مطلق.',
                    'de' => 'Halte eine 365-Tage-Aktivitätsserie aufrecht. Absolute Hingabe.',
                    'zh' => '保持365天连续活跃记录。绝对的专注。',
                    'ru' => 'Поддерживай серию активности 365 дней. Абсолютная преданность.',
                    'hi' => '365 दिन की गतिविधि श्रृंखला बनाए रखें। पूर्ण समर्पण।',
                ],
                'category' => 'streak',
                'xp_reward' => 2000,
                'criteria' => ['type' => 'streak', 'count' => 365, 'rarity' => 'legendary'],
                'sort_order' => 507,
            ],
        ];

        foreach ($badges as $badge) {
            Badge::firstOrCreate(
                ['slug' => $badge['slug']],
                array_merge($badge, ['is_active' => true]),
            );
        }
    }
}
