<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Mission;
use Illuminate\Database\Seeder;

class MissionSeeder extends Seeder
{
    public function run(): void
    {
        $missions = [
            // ── Onboarding (11) — type=one_time ───────────────────────
            [
                'slug' => 'complete_profile',
                'names' => [
                    'en' => 'Complete Your Profile',
                    'fr' => 'Complète ton Profil',
                    'es' => 'Completa tu Perfil',
                    'pt' => 'Complete seu Perfil',
                    'ar' => 'أكمل ملفك الشخصي',
                    'de' => 'Profil vervollständigen',
                    'zh' => '完善个人资料',
                    'ru' => 'Заполни профиль',
                    'hi' => 'प्रोफ़ाइल पूरी करें',
                ],
                'descriptions' => [
                    'en' => 'Fill in all required profile fields to get started.',
                    'fr' => 'Remplis tous les champs requis de ton profil pour commencer.',
                    'es' => 'Completa todos los campos requeridos de tu perfil para comenzar.',
                    'pt' => 'Preencha todos os campos obrigatórios do seu perfil para começar.',
                    'ar' => 'املأ جميع حقول الملف الشخصي المطلوبة للبدء.',
                    'de' => 'Fülle alle erforderlichen Profilfelder aus, um loszulegen.',
                    'zh' => '填写所有必填的个人资料字段以开始使用。',
                    'ru' => 'Заполни все обязательные поля профиля, чтобы начать.',
                    'hi' => 'शुरू करने के लिए सभी आवश्यक प्रोफ़ाइल फ़ील्ड भरें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'profile_complete'],
                'target_count' => 1,
                'xp_reward' => 25,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 100,
            ],
            [
                'slug' => 'share_first_link',
                'names' => [
                    'en' => 'Share Your First Link',
                    'fr' => 'Partage ton Premier Lien',
                    'es' => 'Comparte tu Primer Enlace',
                    'pt' => 'Compartilhe seu Primeiro Link',
                    'ar' => 'شارك رابطك الأول',
                    'de' => 'Teile deinen ersten Link',
                    'zh' => '分享你的首个链接',
                    'ru' => 'Поделись первой ссылкой',
                    'hi' => 'अपना पहला लिंक शेयर करें',
                ],
                'descriptions' => [
                    'en' => 'Share your affiliate link for the first time.',
                    'fr' => 'Partage ton lien affilié pour la première fois.',
                    'es' => 'Comparte tu enlace de afiliado por primera vez.',
                    'pt' => 'Compartilhe seu link de afiliado pela primeira vez.',
                    'ar' => 'شارك رابط الإحالة الخاص بك لأول مرة.',
                    'de' => 'Teile deinen Affiliate-Link zum ersten Mal.',
                    'zh' => '首次分享你的推广链接。',
                    'ru' => 'Поделись своей реферальной ссылкой впервые.',
                    'hi' => 'अपना एफिलिएट लिंक पहली बार शेयर करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'first_share'],
                'target_count' => 1,
                'xp_reward' => 25,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 101,
            ],
            [
                'slug' => 'make_first_sale',
                'names' => [
                    'en' => 'Make Your First Sale',
                    'fr' => 'Fais ta Première Vente',
                    'es' => 'Haz tu Primera Venta',
                    'pt' => 'Faça sua Primeira Venda',
                    'ar' => 'حقق أول عملية بيع',
                    'de' => 'Mach deinen ersten Verkauf',
                    'zh' => '完成首次销售',
                    'ru' => 'Сделай первую продажу',
                    'hi' => 'अपनी पहली बिक्री करें',
                ],
                'descriptions' => [
                    'en' => 'Land your very first client through your affiliate link.',
                    'fr' => 'Décroche ton tout premier client via ton lien affilié.',
                    'es' => 'Consigue tu primer cliente a través de tu enlace de afiliado.',
                    'pt' => 'Conquiste seu primeiro cliente através do seu link de afiliado.',
                    'ar' => 'احصل على أول عميل لك عبر رابط الإحالة.',
                    'de' => 'Gewinne deinen ersten Kunden über deinen Affiliate-Link.',
                    'zh' => '通过你的推广链接获得第一个客户。',
                    'ru' => 'Привлеки первого клиента через свою реферальную ссылку.',
                    'hi' => 'अपने एफिलिएट लिंक से पहला क्लाइंट प्राप्त करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'sales_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 100,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 102,
            ],
            [
                'slug' => 'recruit_first_chatter',
                'names' => [
                    'en' => 'Recruit Your First Chatter',
                    'fr' => 'Recrute ton Premier Chatter',
                    'es' => 'Recluta tu Primer Chatter',
                    'pt' => 'Recrute seu Primeiro Chatter',
                    'ar' => 'جنّد أول شاتر لك',
                    'de' => 'Rekrutiere deinen ersten Chatter',
                    'zh' => '招募你的首个推广员',
                    'ru' => 'Пригласи первого чаттера',
                    'hi' => 'अपना पहला चैटर भर्ती करें',
                ],
                'descriptions' => [
                    'en' => 'Invite someone who successfully registers as a chatter.',
                    'fr' => 'Invite quelqu\'un qui s\'inscrit avec succès comme chatter.',
                    'es' => 'Invita a alguien que se registre exitosamente como chatter.',
                    'pt' => 'Convide alguém que se registre com sucesso como chatter.',
                    'ar' => 'ادعُ شخصًا يسجّل بنجاح كشاتر.',
                    'de' => 'Lade jemanden ein, der sich erfolgreich als Chatter registriert.',
                    'zh' => '邀请一位成功注册为推广员的人。',
                    'ru' => 'Пригласи кого-то, кто успешно зарегистрируется как чаттер.',
                    'hi' => 'किसी को आमंत्रित करें जो सफलतापूर्वक चैटर के रूप में पंजीकृत हो।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'referral_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 100,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 103,
            ],
            [
                'slug' => 'complete_first_training',
                'names' => [
                    'en' => 'Complete First Training',
                    'fr' => 'Termine ta Première Formation',
                    'es' => 'Completa tu Primera Formación',
                    'pt' => 'Complete seu Primeiro Treinamento',
                    'ar' => 'أكمل أول تدريب',
                    'de' => 'Erstes Training abschließen',
                    'zh' => '完成首次培训',
                    'ru' => 'Пройди первое обучение',
                    'hi' => 'पहला प्रशिक्षण पूरा करें',
                ],
                'descriptions' => [
                    'en' => 'Finish your first training module.',
                    'fr' => 'Termine ton premier module de formation.',
                    'es' => 'Termina tu primer módulo de formación.',
                    'pt' => 'Conclua seu primeiro módulo de treinamento.',
                    'ar' => 'أنهِ أول وحدة تدريبية لك.',
                    'de' => 'Schließe dein erstes Trainingsmodul ab.',
                    'zh' => '完成你的第一个培训模块。',
                    'ru' => 'Заверши свой первый учебный модуль.',
                    'hi' => 'अपना पहला प्रशिक्षण मॉड्यूल पूरा करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'training_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 30,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 104,
            ],
            [
                'slug' => 'link_telegram',
                'names' => [
                    'en' => 'Link Telegram',
                    'fr' => 'Lie ton Telegram',
                    'es' => 'Vincula Telegram',
                    'pt' => 'Vincule o Telegram',
                    'ar' => 'اربط تيليجرام',
                    'de' => 'Telegram verknüpfen',
                    'zh' => '绑定Telegram',
                    'ru' => 'Привяжи Telegram',
                    'hi' => 'Telegram जोड़ें',
                ],
                'descriptions' => [
                    'en' => 'Connect your Telegram account to receive notifications.',
                    'fr' => 'Connecte ton compte Telegram pour recevoir les notifications.',
                    'es' => 'Conecta tu cuenta de Telegram para recibir notificaciones.',
                    'pt' => 'Conecte sua conta do Telegram para receber notificações.',
                    'ar' => 'اربط حسابك على تيليجرام لتلقي الإشعارات.',
                    'de' => 'Verbinde dein Telegram-Konto, um Benachrichtigungen zu erhalten.',
                    'zh' => '连接你的Telegram账号以接收通知。',
                    'ru' => 'Подключи свой Telegram-аккаунт для получения уведомлений.',
                    'hi' => 'सूचनाएं प्राप्त करने के लिए अपना Telegram अकाउंट जोड़ें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'telegram_linked'],
                'target_count' => 1,
                'xp_reward' => 50,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 105,
            ],
            [
                'slug' => 'attend_first_zoom',
                'names' => [
                    'en' => 'Attend First Zoom',
                    'fr' => 'Participe à ton Premier Zoom',
                    'es' => 'Asiste a tu Primer Zoom',
                    'pt' => 'Participe do Primeiro Zoom',
                    'ar' => 'احضر أول جلسة Zoom',
                    'de' => 'Erstes Zoom besuchen',
                    'zh' => '参加首次Zoom会议',
                    'ru' => 'Посети первый Zoom',
                    'hi' => 'पहले Zoom में शामिल हों',
                ],
                'descriptions' => [
                    'en' => 'Join your first live Zoom training session.',
                    'fr' => 'Rejoins ta première session de formation Zoom en direct.',
                    'es' => 'Únete a tu primera sesión de formación en vivo por Zoom.',
                    'pt' => 'Participe da sua primeira sessão de treinamento ao vivo no Zoom.',
                    'ar' => 'انضم إلى أول جلسة تدريب مباشرة على Zoom.',
                    'de' => 'Nimm an deiner ersten Live-Zoom-Schulung teil.',
                    'zh' => '加入你的第一次Zoom直播培训课程。',
                    'ru' => 'Присоединись к первой живой Zoom-тренировке.',
                    'hi' => 'अपने पहले लाइव Zoom प्रशिक्षण सत्र में शामिल हों।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'zoom_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 40,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 106,
            ],
            [
                'slug' => 'reach_level_2',
                'names' => [
                    'en' => 'Reach Level 2',
                    'fr' => 'Atteins le Niveau 2',
                    'es' => 'Alcanza el Nivel 2',
                    'pt' => 'Alcance o Nível 2',
                    'ar' => 'ابلغ المستوى 2',
                    'de' => 'Erreiche Level 2',
                    'zh' => '达到2级',
                    'ru' => 'Достигни уровня 2',
                    'hi' => 'लेवल 2 तक पहुँचें',
                ],
                'descriptions' => [
                    'en' => 'Accumulate enough XP to reach level 2.',
                    'fr' => 'Accumule assez d\'XP pour atteindre le niveau 2.',
                    'es' => 'Acumula suficiente XP para alcanzar el nivel 2.',
                    'pt' => 'Acumule XP suficiente para alcançar o nível 2.',
                    'ar' => 'اجمع نقاط خبرة كافية للوصول إلى المستوى 2.',
                    'de' => 'Sammle genug XP, um Level 2 zu erreichen.',
                    'zh' => '积累足够的经验值达到2级。',
                    'ru' => 'Набери достаточно XP, чтобы достичь уровня 2.',
                    'hi' => 'लेवल 2 तक पहुँचने के लिए पर्याप्त XP जमा करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'level', 'count' => 2],
                'target_count' => 1,
                'xp_reward' => 50,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 107,
            ],
            [
                'slug' => 'earn_first_50',
                'names' => [
                    'en' => 'Earn Your First $50',
                    'fr' => 'Gagne tes Premiers 50$',
                    'es' => 'Gana tus Primeros $50',
                    'pt' => 'Ganhe seus Primeiros $50',
                    'ar' => 'اكسب أول $50',
                    'de' => 'Verdiene deine ersten $50',
                    'zh' => '赚到你的首笔$50',
                    'ru' => 'Заработай первые $50',
                    'hi' => 'अपने पहले $50 कमाएँ',
                ],
                'descriptions' => [
                    'en' => 'Reach $50 in total commissions.',
                    'fr' => 'Atteins 50$ de commissions totales.',
                    'es' => 'Alcanza $50 en comisiones totales.',
                    'pt' => 'Alcance $50 em comissões totais.',
                    'ar' => 'اجمع $50 من العمولات الإجمالية.',
                    'de' => 'Erreiche $50 an Gesamtprovisionen.',
                    'zh' => '累计佣金达到$50。',
                    'ru' => 'Достигни $50 общих комиссий.',
                    'hi' => 'कुल कमीशन में $50 तक पहुँचें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'earnings_cents', 'count' => 5000],
                'target_count' => 1,
                'xp_reward' => 75,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 108,
            ],
            [
                'slug' => 'share_on_3_platforms',
                'names' => [
                    'en' => 'Share on 3 Platforms',
                    'fr' => 'Partage sur 3 Plateformes',
                    'es' => 'Comparte en 3 Plataformas',
                    'pt' => 'Compartilhe em 3 Plataformas',
                    'ar' => 'شارك على 3 منصات',
                    'de' => 'Auf 3 Plattformen teilen',
                    'zh' => '在3个平台上分享',
                    'ru' => 'Поделись на 3 платформах',
                    'hi' => '3 प्लेटफ़ॉर्म पर शेयर करें',
                ],
                'descriptions' => [
                    'en' => 'Share your affiliate link on at least 3 different platforms.',
                    'fr' => 'Partage ton lien affilié sur au moins 3 plateformes différentes.',
                    'es' => 'Comparte tu enlace de afiliado en al menos 3 plataformas diferentes.',
                    'pt' => 'Compartilhe seu link de afiliado em pelo menos 3 plataformas diferentes.',
                    'ar' => 'شارك رابط الإحالة على 3 منصات مختلفة على الأقل.',
                    'de' => 'Teile deinen Affiliate-Link auf mindestens 3 verschiedenen Plattformen.',
                    'zh' => '在至少3个不同平台上分享你的推广链接。',
                    'ru' => 'Поделись реферальной ссылкой на минимум 3 разных платформах.',
                    'hi' => 'अपना एफिलिएट लिंक कम से कम 3 अलग-अलग प्लेटफ़ॉर्म पर शेयर करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'multi_platform', 'count' => 3],
                'target_count' => 3,
                'xp_reward' => 75,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 109,
            ],
            [
                'slug' => 'complete_all_onboarding',
                'names' => [
                    'en' => 'Onboarding Complete',
                    'fr' => 'Onboarding Terminé',
                    'es' => 'Onboarding Completo',
                    'pt' => 'Onboarding Concluído',
                    'ar' => 'اكتمل التأهيل',
                    'de' => 'Onboarding abgeschlossen',
                    'zh' => '新手引导完成',
                    'ru' => 'Онбординг завершён',
                    'hi' => 'ऑनबोर्डिंग पूरा',
                ],
                'descriptions' => [
                    'en' => 'Complete all onboarding missions. You\'re ready to crush it!',
                    'fr' => 'Termine toutes les missions d\'onboarding. Tu es prêt à tout déchirer !',
                    'es' => '¡Completa todas las misiones de onboarding. Estás listo para arrasar!',
                    'pt' => 'Complete todas as missões de onboarding. Você está pronto para arrasar!',
                    'ar' => 'أكمل جميع مهام التأهيل. أنت جاهز للانطلاق!',
                    'de' => 'Schließe alle Onboarding-Missionen ab. Du bist bereit durchzustarten!',
                    'zh' => '完成所有新手引导任务，你已准备好大展身手！',
                    'ru' => 'Выполни все миссии онбординга. Ты готов покорять вершины!',
                    'hi' => 'सभी ऑनबोर्डिंग मिशन पूरे करें। आप शुरू करने के लिए तैयार हैं!',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'all_onboarding_complete'],
                'target_count' => 1,
                'xp_reward' => 200,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 110,
            ],

            // ── Daily (12) — 3 shown per day ─────────────────────────
            [
                'slug' => 'share_link_today',
                'names' => [
                    'en' => 'Share Your Link',
                    'fr' => 'Partage ton Lien',
                    'es' => 'Comparte tu Enlace',
                    'pt' => 'Compartilhe seu Link',
                    'ar' => 'شارك رابطك',
                    'de' => 'Teile deinen Link',
                    'zh' => '分享你的链接',
                    'ru' => 'Поделись ссылкой',
                    'hi' => 'अपना लिंक शेयर करें',
                ],
                'descriptions' => [
                    'en' => 'Share your affiliate link at least once today.',
                    'fr' => 'Partage ton lien affilié au moins une fois aujourd\'hui.',
                    'es' => 'Comparte tu enlace de afiliado al menos una vez hoy.',
                    'pt' => 'Compartilhe seu link de afiliado pelo menos uma vez hoje.',
                    'ar' => 'شارك رابط الإحالة مرة واحدة على الأقل اليوم.',
                    'de' => 'Teile deinen Affiliate-Link heute mindestens einmal.',
                    'zh' => '今天至少分享一次你的推广链接。',
                    'ru' => 'Поделись реферальной ссылкой хотя бы раз сегодня.',
                    'hi' => 'आज अपना एफिलिएट लिंक कम से कम एक बार शेयर करें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'share_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 10,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 200,
            ],
            [
                'slug' => 'make_sale_today',
                'names' => [
                    'en' => 'Make a Sale',
                    'fr' => 'Fais une Vente',
                    'es' => 'Haz una Venta',
                    'pt' => 'Faça uma Venda',
                    'ar' => 'حقق عملية بيع',
                    'de' => 'Mach einen Verkauf',
                    'zh' => '完成一笔销售',
                    'ru' => 'Сделай продажу',
                    'hi' => 'एक बिक्री करें',
                ],
                'descriptions' => [
                    'en' => 'Close at least one sale today.',
                    'fr' => 'Conclus au moins une vente aujourd\'hui.',
                    'es' => 'Cierra al menos una venta hoy.',
                    'pt' => 'Feche pelo menos uma venda hoje.',
                    'ar' => 'أتمم عملية بيع واحدة على الأقل اليوم.',
                    'de' => 'Schließe heute mindestens einen Verkauf ab.',
                    'zh' => '今天至少完成一笔销售。',
                    'ru' => 'Закрой хотя бы одну сделку сегодня.',
                    'hi' => 'आज कम से कम एक बिक्री पूरी करें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'sales_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 50,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 201,
            ],
            [
                'slug' => 'check_dashboard',
                'names' => [
                    'en' => 'Check Dashboard',
                    'fr' => 'Consulte le Dashboard',
                    'es' => 'Revisa el Dashboard',
                    'pt' => 'Confira o Dashboard',
                    'ar' => 'تحقق من لوحة التحكم',
                    'de' => 'Dashboard prüfen',
                    'zh' => '查看仪表盘',
                    'ru' => 'Проверь дашборд',
                    'hi' => 'डैशबोर्ड देखें',
                ],
                'descriptions' => [
                    'en' => 'Visit your dashboard today.',
                    'fr' => 'Visite ton tableau de bord aujourd\'hui.',
                    'es' => 'Visita tu panel de control hoy.',
                    'pt' => 'Visite seu painel de controle hoje.',
                    'ar' => 'قم بزيارة لوحة التحكم اليوم.',
                    'de' => 'Besuche heute dein Dashboard.',
                    'zh' => '今天访问你的仪表盘。',
                    'ru' => 'Зайди в свой дашборд сегодня.',
                    'hi' => 'आज अपना डैशबोर्ड देखें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'dashboard_visit', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 5,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 202,
            ],
            [
                'slug' => 'share_on_social',
                'names' => [
                    'en' => 'Share on Social Media',
                    'fr' => 'Partage sur les Réseaux',
                    'es' => 'Comparte en Redes Sociales',
                    'pt' => 'Compartilhe nas Redes',
                    'ar' => 'شارك على وسائل التواصل',
                    'de' => 'In sozialen Medien teilen',
                    'zh' => '在社交媒体分享',
                    'ru' => 'Поделись в соцсетях',
                    'hi' => 'सोशल मीडिया पर शेयर करें',
                ],
                'descriptions' => [
                    'en' => 'Post your link on a social media platform.',
                    'fr' => 'Publie ton lien sur un réseau social.',
                    'es' => 'Publica tu enlace en una red social.',
                    'pt' => 'Publique seu link em uma rede social.',
                    'ar' => 'انشر رابطك على منصة تواصل اجتماعي.',
                    'de' => 'Poste deinen Link auf einer Social-Media-Plattform.',
                    'zh' => '在社交媒体平台上发布你的链接。',
                    'ru' => 'Опубликуй свою ссылку в социальной сети.',
                    'hi' => 'सोशल मीडिया प्लेटफ़ॉर्म पर अपना लिंक पोस्ट करें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'social_share', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 10,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 203,
            ],
            [
                'slug' => 'recruit_today',
                'names' => [
                    'en' => 'Recruit Today',
                    'fr' => 'Recrute Aujourd\'hui',
                    'es' => 'Recluta Hoy',
                    'pt' => 'Recrute Hoje',
                    'ar' => 'جنّد اليوم',
                    'de' => 'Rekrutiere heute',
                    'zh' => '今天招募',
                    'ru' => 'Пригласи сегодня',
                    'hi' => 'आज भर्ती करें',
                ],
                'descriptions' => [
                    'en' => 'Get someone to sign up as a chatter today.',
                    'fr' => 'Fais inscrire quelqu\'un comme chatter aujourd\'hui.',
                    'es' => 'Haz que alguien se registre como chatter hoy.',
                    'pt' => 'Faça alguém se cadastrar como chatter hoje.',
                    'ar' => 'اجعل شخصًا يسجّل كشاتر اليوم.',
                    'de' => 'Bringe heute jemanden dazu, sich als Chatter anzumelden.',
                    'zh' => '今天让一个人注册为推广员。',
                    'ru' => 'Сделай так, чтобы кто-то зарегистрировался как чаттер сегодня.',
                    'hi' => 'आज किसी को चैटर के रूप में साइन अप कराएँ।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'referral_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 75,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 204,
            ],
            [
                'slug' => 'complete_training_module',
                'names' => [
                    'en' => 'Complete a Training',
                    'fr' => 'Termine une Formation',
                    'es' => 'Completa una Formación',
                    'pt' => 'Complete um Treinamento',
                    'ar' => 'أكمل تدريبًا',
                    'de' => 'Training abschließen',
                    'zh' => '完成一次培训',
                    'ru' => 'Пройди обучение',
                    'hi' => 'एक प्रशिक्षण पूरा करें',
                ],
                'descriptions' => [
                    'en' => 'Complete one training module today.',
                    'fr' => 'Termine un module de formation aujourd\'hui.',
                    'es' => 'Completa un módulo de formación hoy.',
                    'pt' => 'Complete um módulo de treinamento hoje.',
                    'ar' => 'أكمل وحدة تدريبية واحدة اليوم.',
                    'de' => 'Schließe heute ein Trainingsmodul ab.',
                    'zh' => '今天完成一个培训模块。',
                    'ru' => 'Заверши один учебный модуль сегодня.',
                    'hi' => 'आज एक प्रशिक्षण मॉड्यूल पूरा करें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'training_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 20,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 205,
            ],
            [
                'slug' => 'check_leaderboard',
                'names' => [
                    'en' => 'Check Leaderboard',
                    'fr' => 'Consulte le Classement',
                    'es' => 'Revisa la Clasificación',
                    'pt' => 'Confira o Ranking',
                    'ar' => 'تحقق من لوحة المتصدرين',
                    'de' => 'Rangliste prüfen',
                    'zh' => '查看排行榜',
                    'ru' => 'Проверь рейтинг',
                    'hi' => 'लीडरबोर्ड देखें',
                ],
                'descriptions' => [
                    'en' => 'View the leaderboard today.',
                    'fr' => 'Consulte le classement aujourd\'hui.',
                    'es' => 'Consulta la clasificación hoy.',
                    'pt' => 'Veja o ranking hoje.',
                    'ar' => 'اطّلع على لوحة المتصدرين اليوم.',
                    'de' => 'Sieh dir heute die Rangliste an.',
                    'zh' => '今天查看排行榜。',
                    'ru' => 'Посмотри таблицу лидеров сегодня.',
                    'hi' => 'आज लीडरबोर्ड देखें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'leaderboard_visit', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 5,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 206,
            ],
            [
                'slug' => 'share_earnings_screenshot',
                'names' => [
                    'en' => 'Share Earnings Screenshot',
                    'fr' => 'Partage une Capture de Gains',
                    'es' => 'Comparte Captura de Ganancias',
                    'pt' => 'Compartilhe Print dos Ganhos',
                    'ar' => 'شارك لقطة أرباحك',
                    'de' => 'Verdienst-Screenshot teilen',
                    'zh' => '分享收益截图',
                    'ru' => 'Поделись скриншотом заработка',
                    'hi' => 'कमाई का स्क्रीनशॉट शेयर करें',
                ],
                'descriptions' => [
                    'en' => 'Share a screenshot of your earnings on social media.',
                    'fr' => 'Partage une capture d\'écran de tes gains sur les réseaux.',
                    'es' => 'Comparte una captura de pantalla de tus ganancias en redes sociales.',
                    'pt' => 'Compartilhe uma captura de tela dos seus ganhos nas redes sociais.',
                    'ar' => 'شارك لقطة شاشة لأرباحك على وسائل التواصل.',
                    'de' => 'Teile einen Screenshot deiner Verdienste in sozialen Medien.',
                    'zh' => '在社交媒体上分享你的收益截图。',
                    'ru' => 'Поделись скриншотом своих доходов в соцсетях.',
                    'hi' => 'सोशल मीडिया पर अपनी कमाई का स्क्रीनशॉट शेयर करें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'earnings_screenshot_shared', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 15,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 207,
            ],
            [
                'slug' => 'post_in_group',
                'names' => [
                    'en' => 'Post in Group',
                    'fr' => 'Publie dans le Groupe',
                    'es' => 'Publica en el Grupo',
                    'pt' => 'Publique no Grupo',
                    'ar' => 'انشر في المجموعة',
                    'de' => 'In Gruppe posten',
                    'zh' => '在群组中发帖',
                    'ru' => 'Опубликуй в группе',
                    'hi' => 'ग्रुप में पोस्ट करें',
                ],
                'descriptions' => [
                    'en' => 'Post your link in a group or community.',
                    'fr' => 'Publie ton lien dans un groupe ou une communauté.',
                    'es' => 'Publica tu enlace en un grupo o comunidad.',
                    'pt' => 'Publique seu link em um grupo ou comunidade.',
                    'ar' => 'انشر رابطك في مجموعة أو مجتمع.',
                    'de' => 'Poste deinen Link in einer Gruppe oder Community.',
                    'zh' => '在群组或社区中发布你的链接。',
                    'ru' => 'Опубликуй свою ссылку в группе или сообществе.',
                    'hi' => 'किसी ग्रुप या कम्युनिटी में अपना लिंक पोस्ट करें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'group_post', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 10,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 208,
            ],
            [
                'slug' => 'refer_from_new_country',
                'names' => [
                    'en' => 'New Country Referral',
                    'fr' => 'Referral d\'un Nouveau Pays',
                    'es' => 'Referido de Nuevo País',
                    'pt' => 'Indicação de Novo País',
                    'ar' => 'إحالة من بلد جديد',
                    'de' => 'Empfehlung aus neuem Land',
                    'zh' => '新国家推荐',
                    'ru' => 'Реферал из новой страны',
                    'hi' => 'नए देश से रेफरल',
                ],
                'descriptions' => [
                    'en' => 'Get a client from a country you haven\'t sold to before.',
                    'fr' => 'Obtiens un client d\'un pays où tu n\'as jamais vendu.',
                    'es' => 'Consigue un cliente de un país donde nunca hayas vendido.',
                    'pt' => 'Consiga um cliente de um país para o qual você nunca vendeu.',
                    'ar' => 'احصل على عميل من بلد لم تبع فيه من قبل.',
                    'de' => 'Gewinne einen Kunden aus einem Land, in dem du noch nie verkauft hast.',
                    'zh' => '从一个你从未销售过的国家获取客户。',
                    'ru' => 'Привлеки клиента из страны, в которой ты ещё не продавал.',
                    'hi' => 'किसी ऐसे देश से क्लाइंट प्राप्त करें जहाँ आपने पहले कभी नहीं बेचा।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'new_country_sale', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 30,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 209,
            ],
            [
                'slug' => 'earn_10_today',
                'names' => [
                    'en' => 'Earn $10 Today',
                    'fr' => 'Gagne 10$ Aujourd\'hui',
                    'es' => 'Gana $10 Hoy',
                    'pt' => 'Ganhe $10 Hoje',
                    'ar' => 'اكسب $10 اليوم',
                    'de' => 'Verdiene heute $10',
                    'zh' => '今天赚$10',
                    'ru' => 'Заработай $10 сегодня',
                    'hi' => 'आज $10 कमाएँ',
                ],
                'descriptions' => [
                    'en' => 'Earn at least $10 in commissions today.',
                    'fr' => 'Gagne au moins 10$ de commissions aujourd\'hui.',
                    'es' => 'Gana al menos $10 en comisiones hoy.',
                    'pt' => 'Ganhe pelo menos $10 em comissões hoje.',
                    'ar' => 'اكسب $10 على الأقل من العمولات اليوم.',
                    'de' => 'Verdiene heute mindestens $10 an Provisionen.',
                    'zh' => '今天至少赚取$10佣金。',
                    'ru' => 'Заработай сегодня минимум $10 комиссий.',
                    'hi' => 'आज कम से कम $10 कमीशन कमाएँ।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'daily_earnings_cents', 'count' => 1000],
                'target_count' => 1,
                'xp_reward' => 40,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 210,
            ],
            [
                'slug' => 'watch_tutorial',
                'names' => [
                    'en' => 'Watch a Tutorial',
                    'fr' => 'Regarde un Tutoriel',
                    'es' => 'Mira un Tutorial',
                    'pt' => 'Assista um Tutorial',
                    'ar' => 'شاهد درسًا تعليميًا',
                    'de' => 'Tutorial ansehen',
                    'zh' => '观看教程',
                    'ru' => 'Посмотри урок',
                    'hi' => 'एक ट्यूटोरियल देखें',
                ],
                'descriptions' => [
                    'en' => 'Watch a training video or tutorial today.',
                    'fr' => 'Regarde une vidéo de formation ou un tutoriel aujourd\'hui.',
                    'es' => 'Mira un video de formación o tutorial hoy.',
                    'pt' => 'Assista a um vídeo de treinamento ou tutorial hoje.',
                    'ar' => 'شاهد فيديو تدريبي أو درسًا تعليميًا اليوم.',
                    'de' => 'Sieh dir heute ein Trainingsvideo oder Tutorial an.',
                    'zh' => '今天观看一个培训视频或教程。',
                    'ru' => 'Посмотри обучающее видео или урок сегодня.',
                    'hi' => 'आज एक प्रशिक्षण वीडियो या ट्यूटोरियल देखें।',
                ],
                'type' => 'daily',
                'criteria' => ['type' => 'tutorial_watched', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 10,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 211,
            ],

            // ── Weekly (10) ──────────────────────────────────────────
            [
                'slug' => 'sales_3_week',
                'names' => [
                    'en' => '3 Sales This Week',
                    'fr' => '3 Ventes cette Semaine',
                    'es' => '3 Ventas esta Semana',
                    'pt' => '3 Vendas esta Semana',
                    'ar' => '3 مبيعات هذا الأسبوع',
                    'de' => '3 Verkäufe diese Woche',
                    'zh' => '本周3笔销售',
                    'ru' => '3 продажи за неделю',
                    'hi' => 'इस हफ़्ते 3 बिक्री',
                ],
                'descriptions' => [
                    'en' => 'Close 3 sales this week.',
                    'fr' => 'Conclus 3 ventes cette semaine.',
                    'es' => 'Cierra 3 ventas esta semana.',
                    'pt' => 'Feche 3 vendas esta semana.',
                    'ar' => 'أتمم 3 عمليات بيع هذا الأسبوع.',
                    'de' => 'Schließe diese Woche 3 Verkäufe ab.',
                    'zh' => '本周完成3笔销售。',
                    'ru' => 'Закрой 3 сделки на этой неделе.',
                    'hi' => 'इस हफ़्ते 3 बिक्री पूरी करें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'sales_count', 'count' => 3],
                'target_count' => 3,
                'xp_reward' => 100,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 300,
            ],
            [
                'slug' => 'share_5_week',
                'names' => [
                    'en' => '5 Shares This Week',
                    'fr' => '5 Partages cette Semaine',
                    'es' => '5 Compartidos esta Semana',
                    'pt' => '5 Compartilhamentos esta Semana',
                    'ar' => '5 مشاركات هذا الأسبوع',
                    'de' => '5 Mal teilen diese Woche',
                    'zh' => '本周分享5次',
                    'ru' => '5 публикаций за неделю',
                    'hi' => 'इस हफ़्ते 5 शेयर',
                ],
                'descriptions' => [
                    'en' => 'Share your link 5 times this week.',
                    'fr' => 'Partage ton lien 5 fois cette semaine.',
                    'es' => 'Comparte tu enlace 5 veces esta semana.',
                    'pt' => 'Compartilhe seu link 5 vezes esta semana.',
                    'ar' => 'شارك رابطك 5 مرات هذا الأسبوع.',
                    'de' => 'Teile deinen Link diese Woche 5 Mal.',
                    'zh' => '本周分享你的链接5次。',
                    'ru' => 'Поделись ссылкой 5 раз на этой неделе.',
                    'hi' => 'इस हफ़्ते अपना लिंक 5 बार शेयर करें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'share_count', 'count' => 5],
                'target_count' => 5,
                'xp_reward' => 30,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 301,
            ],
            [
                'slug' => 'refer_friend_week',
                'names' => [
                    'en' => 'Refer a Friend',
                    'fr' => 'Parraine un Ami',
                    'es' => 'Recomienda a un Amigo',
                    'pt' => 'Indique um Amigo',
                    'ar' => 'أحل صديقًا',
                    'de' => 'Empfiehl einen Freund',
                    'zh' => '推荐一位朋友',
                    'ru' => 'Пригласи друга',
                    'hi' => 'एक दोस्त को रेफर करें',
                ],
                'descriptions' => [
                    'en' => 'Recruit at least one new chatter this week.',
                    'fr' => 'Recrute au moins un nouveau chatter cette semaine.',
                    'es' => 'Recluta al menos un nuevo chatter esta semana.',
                    'pt' => 'Recrute pelo menos um novo chatter esta semana.',
                    'ar' => 'جنّد شاتر جديد واحد على الأقل هذا الأسبوع.',
                    'de' => 'Rekrutiere diese Woche mindestens einen neuen Chatter.',
                    'zh' => '本周至少招募一名新推广员。',
                    'ru' => 'Пригласи минимум одного нового чаттера на этой неделе.',
                    'hi' => 'इस हफ़्ते कम से कम एक नया चैटर भर्ती करें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'referral_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 75,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 302,
            ],
            [
                'slug' => 'complete_2_trainings_week',
                'names' => [
                    'en' => '2 Trainings This Week',
                    'fr' => '2 Formations cette Semaine',
                    'es' => '2 Formaciones esta Semana',
                    'pt' => '2 Treinamentos esta Semana',
                    'ar' => '2 تدريبات هذا الأسبوع',
                    'de' => '2 Trainings diese Woche',
                    'zh' => '本周2次培训',
                    'ru' => '2 обучения за неделю',
                    'hi' => 'इस हफ़्ते 2 प्रशिक्षण',
                ],
                'descriptions' => [
                    'en' => 'Complete 2 training modules this week.',
                    'fr' => 'Termine 2 modules de formation cette semaine.',
                    'es' => 'Completa 2 módulos de formación esta semana.',
                    'pt' => 'Complete 2 módulos de treinamento esta semana.',
                    'ar' => 'أكمل وحدتين تدريبيتين هذا الأسبوع.',
                    'de' => 'Schließe diese Woche 2 Trainingsmodule ab.',
                    'zh' => '本周完成2个培训模块。',
                    'ru' => 'Заверши 2 учебных модуля на этой неделе.',
                    'hi' => 'इस हफ़्ते 2 प्रशिक्षण मॉड्यूल पूरे करें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'training_count', 'count' => 2],
                'target_count' => 2,
                'xp_reward' => 50,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 303,
            ],
            [
                'slug' => 'maintain_streak_7',
                'names' => [
                    'en' => 'Maintain 7-Day Streak',
                    'fr' => 'Maintiens une Série de 7 Jours',
                    'es' => 'Mantén Racha de 7 Días',
                    'pt' => 'Mantenha Sequência de 7 Dias',
                    'ar' => 'حافظ على سلسلة 7 أيام',
                    'de' => '7-Tage-Serie halten',
                    'zh' => '保持7天连续活跃',
                    'ru' => 'Серия 7 дней подряд',
                    'hi' => '7 दिन की स्ट्रीक बनाए रखें',
                ],
                'descriptions' => [
                    'en' => 'Keep your activity streak going for 7 consecutive days.',
                    'fr' => 'Maintiens ta série d\'activité pendant 7 jours consécutifs.',
                    'es' => 'Mantén tu racha de actividad durante 7 días consecutivos.',
                    'pt' => 'Mantenha sua sequência de atividade por 7 dias consecutivos.',
                    'ar' => 'حافظ على سلسلة نشاطك لمدة 7 أيام متتالية.',
                    'de' => 'Halte deine Aktivitätsserie 7 Tage in Folge aufrecht.',
                    'zh' => '连续7天保持活跃。',
                    'ru' => 'Поддерживай серию активности 7 дней подряд.',
                    'hi' => 'लगातार 7 दिनों तक अपनी एक्टिविटी स्ट्रीक जारी रखें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'streak', 'count' => 7],
                'target_count' => 7,
                'xp_reward' => 75,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 304,
            ],
            [
                'slug' => 'top_10_leaderboard_week',
                'names' => [
                    'en' => 'Top 10 Leaderboard',
                    'fr' => 'Top 10 du Classement',
                    'es' => 'Top 10 del Ranking',
                    'pt' => 'Top 10 do Ranking',
                    'ar' => 'أفضل 10 في الترتيب',
                    'de' => 'Top 10 der Rangliste',
                    'zh' => '排行榜前10名',
                    'ru' => 'Топ-10 рейтинга',
                    'hi' => 'लीडरबोर्ड में टॉप 10',
                ],
                'descriptions' => [
                    'en' => 'Finish in the top 10 of the weekly leaderboard.',
                    'fr' => 'Termine dans le top 10 du classement hebdomadaire.',
                    'es' => 'Termina en el top 10 del ranking semanal.',
                    'pt' => 'Termine entre os 10 primeiros do ranking semanal.',
                    'ar' => 'احتل مركزًا ضمن أفضل 10 في الترتيب الأسبوعي.',
                    'de' => 'Lande in den Top 10 der wöchentlichen Rangliste.',
                    'zh' => '进入每周排行榜前10名。',
                    'ru' => 'Попади в топ-10 еженедельного рейтинга.',
                    'hi' => 'साप्ताहिक लीडरबोर्ड में टॉप 10 में आएँ।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'leaderboard_weekly_top', 'count' => 10],
                'target_count' => 1,
                'xp_reward' => 100,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 305,
            ],
            [
                'slug' => 'recruit_2_week',
                'names' => [
                    'en' => 'Recruit 2 This Week',
                    'fr' => 'Recrute 2 cette Semaine',
                    'es' => 'Recluta 2 esta Semana',
                    'pt' => 'Recrute 2 esta Semana',
                    'ar' => 'جنّد 2 هذا الأسبوع',
                    'de' => 'Rekrutiere 2 diese Woche',
                    'zh' => '本周招募2人',
                    'ru' => 'Пригласи 2 за неделю',
                    'hi' => 'इस हफ़्ते 2 भर्ती करें',
                ],
                'descriptions' => [
                    'en' => 'Recruit 2 new chatters this week.',
                    'fr' => 'Recrute 2 nouveaux chatters cette semaine.',
                    'es' => 'Recluta 2 nuevos chatters esta semana.',
                    'pt' => 'Recrute 2 novos chatters esta semana.',
                    'ar' => 'جنّد شاترين جديدين هذا الأسبوع.',
                    'de' => 'Rekrutiere diese Woche 2 neue Chatter.',
                    'zh' => '本周招募2名新推广员。',
                    'ru' => 'Пригласи 2 новых чаттеров на этой неделе.',
                    'hi' => 'इस हफ़्ते 2 नए चैटर भर्ती करें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'referral_count', 'count' => 2],
                'target_count' => 2,
                'xp_reward' => 150,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 306,
            ],
            [
                'slug' => 'earn_100_week',
                'names' => [
                    'en' => 'Earn $100 This Week',
                    'fr' => 'Gagne 100$ cette Semaine',
                    'es' => 'Gana $100 esta Semana',
                    'pt' => 'Ganhe $100 esta Semana',
                    'ar' => 'اكسب $100 هذا الأسبوع',
                    'de' => 'Verdiene $100 diese Woche',
                    'zh' => '本周赚$100',
                    'ru' => 'Заработай $100 за неделю',
                    'hi' => 'इस हफ़्ते $100 कमाएँ',
                ],
                'descriptions' => [
                    'en' => 'Earn $100 in commissions this week.',
                    'fr' => 'Gagne 100$ de commissions cette semaine.',
                    'es' => 'Gana $100 en comisiones esta semana.',
                    'pt' => 'Ganhe $100 em comissões esta semana.',
                    'ar' => 'اكسب $100 من العمولات هذا الأسبوع.',
                    'de' => 'Verdiene diese Woche $100 an Provisionen.',
                    'zh' => '本周赚取$100佣金。',
                    'ru' => 'Заработай $100 комиссий на этой неделе.',
                    'hi' => 'इस हफ़्ते $100 कमीशन कमाएँ।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'weekly_earnings_cents', 'count' => 10000],
                'target_count' => 1,
                'xp_reward' => 150,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 307,
            ],
            [
                'slug' => '5_different_countries_week',
                'names' => [
                    'en' => '5 Different Countries',
                    'fr' => '5 Pays Différents',
                    'es' => '5 Países Diferentes',
                    'pt' => '5 Países Diferentes',
                    'ar' => '5 دول مختلفة',
                    'de' => '5 verschiedene Länder',
                    'zh' => '5个不同国家',
                    'ru' => '5 разных стран',
                    'hi' => '5 अलग-अलग देश',
                ],
                'descriptions' => [
                    'en' => 'Get clients from 5 different countries this week.',
                    'fr' => 'Obtiens des clients de 5 pays différents cette semaine.',
                    'es' => 'Consigue clientes de 5 países diferentes esta semana.',
                    'pt' => 'Consiga clientes de 5 países diferentes esta semana.',
                    'ar' => 'احصل على عملاء من 5 دول مختلفة هذا الأسبوع.',
                    'de' => 'Gewinne diese Woche Kunden aus 5 verschiedenen Ländern.',
                    'zh' => '本周从5个不同国家获取客户。',
                    'ru' => 'Привлеки клиентов из 5 разных стран на этой неделе.',
                    'hi' => 'इस हफ़्ते 5 अलग-अलग देशों से क्लाइंट प्राप्त करें।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'distinct_countries', 'count' => 5],
                'target_count' => 5,
                'xp_reward' => 200,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 308,
            ],
            [
                'slug' => 'attend_zoom_week',
                'names' => [
                    'en' => 'Attend Zoom This Week',
                    'fr' => 'Participe au Zoom cette Semaine',
                    'es' => 'Asiste al Zoom esta Semana',
                    'pt' => 'Participe do Zoom esta Semana',
                    'ar' => 'احضر جلسة Zoom هذا الأسبوع',
                    'de' => 'Zoom diese Woche besuchen',
                    'zh' => '本周参加Zoom',
                    'ru' => 'Посети Zoom на этой неделе',
                    'hi' => 'इस हफ़्ते Zoom में शामिल हों',
                ],
                'descriptions' => [
                    'en' => 'Join a Zoom training session this week.',
                    'fr' => 'Rejoins une session Zoom cette semaine.',
                    'es' => 'Únete a una sesión de formación por Zoom esta semana.',
                    'pt' => 'Participe de uma sessão de treinamento no Zoom esta semana.',
                    'ar' => 'انضم إلى جلسة تدريب على Zoom هذا الأسبوع.',
                    'de' => 'Nimm diese Woche an einer Zoom-Schulung teil.',
                    'zh' => '本周参加一次Zoom培训课程。',
                    'ru' => 'Присоединись к Zoom-тренировке на этой неделе.',
                    'hi' => 'इस हफ़्ते एक Zoom प्रशिक्षण सत्र में शामिल हों।',
                ],
                'type' => 'weekly',
                'criteria' => ['type' => 'zoom_count', 'count' => 1],
                'target_count' => 1,
                'xp_reward' => 40,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 309,
            ],

            // ── Monthly (7) ─────────────────────────────────────────
            [
                'slug' => 'sales_10_month',
                'names' => [
                    'en' => '10 Sales This Month',
                    'fr' => '10 Ventes ce Mois',
                    'es' => '10 Ventas este Mes',
                    'pt' => '10 Vendas este Mês',
                    'ar' => '10 مبيعات هذا الشهر',
                    'de' => '10 Verkäufe diesen Monat',
                    'zh' => '本月10笔销售',
                    'ru' => '10 продаж за месяц',
                    'hi' => 'इस महीने 10 बिक्री',
                ],
                'descriptions' => [
                    'en' => 'Close 10 sales this month.',
                    'fr' => 'Conclus 10 ventes ce mois-ci.',
                    'es' => 'Cierra 10 ventas este mes.',
                    'pt' => 'Feche 10 vendas este mês.',
                    'ar' => 'أتمم 10 عمليات بيع هذا الشهر.',
                    'de' => 'Schließe diesen Monat 10 Verkäufe ab.',
                    'zh' => '本月完成10笔销售。',
                    'ru' => 'Закрой 10 сделок в этом месяце.',
                    'hi' => 'इस महीने 10 बिक्री पूरी करें।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'sales_count', 'count' => 10],
                'target_count' => 10,
                'xp_reward' => 300,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 400,
            ],
            [
                'slug' => 'earn_500_month',
                'names' => [
                    'en' => 'Earn $500 This Month',
                    'fr' => 'Gagne 500$ ce Mois',
                    'es' => 'Gana $500 este Mes',
                    'pt' => 'Ganhe $500 este Mês',
                    'ar' => 'اكسب $500 هذا الشهر',
                    'de' => 'Verdiene $500 diesen Monat',
                    'zh' => '本月赚$500',
                    'ru' => 'Заработай $500 за месяц',
                    'hi' => 'इस महीने $500 कमाएँ',
                ],
                'descriptions' => [
                    'en' => 'Earn $500 in commissions this month.',
                    'fr' => 'Gagne 500$ de commissions ce mois-ci.',
                    'es' => 'Gana $500 en comisiones este mes.',
                    'pt' => 'Ganhe $500 em comissões este mês.',
                    'ar' => 'اكسب $500 من العمولات هذا الشهر.',
                    'de' => 'Verdiene diesen Monat $500 an Provisionen.',
                    'zh' => '本月赚取$500佣金。',
                    'ru' => 'Заработай $500 комиссий в этом месяце.',
                    'hi' => 'इस महीने $500 कमीशन कमाएँ।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'monthly_earnings_cents', 'count' => 50000],
                'target_count' => 1,
                'xp_reward' => 500,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 401,
            ],
            [
                'slug' => 'recruit_5_month',
                'names' => [
                    'en' => 'Recruit 5 This Month',
                    'fr' => 'Recrute 5 ce Mois',
                    'es' => 'Recluta 5 este Mes',
                    'pt' => 'Recrute 5 este Mês',
                    'ar' => 'جنّد 5 هذا الشهر',
                    'de' => 'Rekrutiere 5 diesen Monat',
                    'zh' => '本月招募5人',
                    'ru' => 'Пригласи 5 за месяц',
                    'hi' => 'इस महीने 5 भर्ती करें',
                ],
                'descriptions' => [
                    'en' => 'Recruit 5 new chatters this month.',
                    'fr' => 'Recrute 5 nouveaux chatters ce mois-ci.',
                    'es' => 'Recluta 5 nuevos chatters este mes.',
                    'pt' => 'Recrute 5 novos chatters este mês.',
                    'ar' => 'جنّد 5 شاترات جدد هذا الشهر.',
                    'de' => 'Rekrutiere diesen Monat 5 neue Chatter.',
                    'zh' => '本月招募5名新推广员。',
                    'ru' => 'Пригласи 5 новых чаттеров в этом месяце.',
                    'hi' => 'इस महीने 5 नए चैटर भर्ती करें।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'referral_count', 'count' => 5],
                'target_count' => 5,
                'xp_reward' => 300,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 402,
            ],
            [
                'slug' => 'streak_30_month',
                'names' => [
                    'en' => '30-Day Streak',
                    'fr' => 'Série de 30 Jours',
                    'es' => 'Racha de 30 Días',
                    'pt' => 'Sequência de 30 Dias',
                    'ar' => 'سلسلة 30 يومًا',
                    'de' => '30-Tage-Serie',
                    'zh' => '30天连续活跃',
                    'ru' => 'Серия 30 дней',
                    'hi' => '30 दिन की स्ट्रीक',
                ],
                'descriptions' => [
                    'en' => 'Maintain a 30-day streak within this month.',
                    'fr' => 'Maintiens une série de 30 jours ce mois-ci.',
                    'es' => 'Mantén una racha de 30 días este mes.',
                    'pt' => 'Mantenha uma sequência de 30 dias este mês.',
                    'ar' => 'حافظ على سلسلة نشاط لمدة 30 يومًا هذا الشهر.',
                    'de' => 'Halte diesen Monat eine 30-Tage-Serie aufrecht.',
                    'zh' => '本月保持30天连续活跃。',
                    'ru' => 'Поддерживай серию в 30 дней в этом месяце.',
                    'hi' => 'इस महीने 30 दिन की स्ट्रीक बनाए रखें।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'streak', 'count' => 30],
                'target_count' => 30,
                'xp_reward' => 300,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 403,
            ],
            [
                'slug' => 'top_3_leaderboard_month',
                'names' => [
                    'en' => 'Top 3 Leaderboard',
                    'fr' => 'Top 3 du Classement',
                    'es' => 'Top 3 del Ranking',
                    'pt' => 'Top 3 do Ranking',
                    'ar' => 'أفضل 3 في الترتيب',
                    'de' => 'Top 3 der Rangliste',
                    'zh' => '排行榜前3名',
                    'ru' => 'Топ-3 рейтинга',
                    'hi' => 'लीडरबोर्ड में टॉप 3',
                ],
                'descriptions' => [
                    'en' => 'Finish in the top 3 of the monthly leaderboard.',
                    'fr' => 'Termine dans le top 3 du classement mensuel.',
                    'es' => 'Termina en el top 3 del ranking mensual.',
                    'pt' => 'Termine entre os 3 primeiros do ranking mensal.',
                    'ar' => 'احتل مركزًا ضمن أفضل 3 في الترتيب الشهري.',
                    'de' => 'Lande in den Top 3 der monatlichen Rangliste.',
                    'zh' => '进入每月排行榜前3名。',
                    'ru' => 'Попади в топ-3 ежемесячного рейтинга.',
                    'hi' => 'मासिक लीडरबोर्ड में टॉप 3 में आएँ।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'leaderboard_monthly_top', 'count' => 3],
                'target_count' => 1,
                'xp_reward' => 500,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 404,
            ],
            [
                'slug' => 'complete_all_trainings_month',
                'names' => [
                    'en' => 'Complete All Trainings',
                    'fr' => 'Termine Toutes les Formations',
                    'es' => 'Completa Todas las Formaciones',
                    'pt' => 'Complete Todos os Treinamentos',
                    'ar' => 'أكمل جميع التدريبات',
                    'de' => 'Alle Trainings abschließen',
                    'zh' => '完成所有培训',
                    'ru' => 'Пройди все обучения',
                    'hi' => 'सभी प्रशिक्षण पूरे करें',
                ],
                'descriptions' => [
                    'en' => 'Finish every available training module this month.',
                    'fr' => 'Termine tous les modules de formation disponibles ce mois-ci.',
                    'es' => 'Termina todos los módulos de formación disponibles este mes.',
                    'pt' => 'Conclua todos os módulos de treinamento disponíveis este mês.',
                    'ar' => 'أنهِ جميع وحدات التدريب المتاحة هذا الشهر.',
                    'de' => 'Schließe diesen Monat alle verfügbaren Trainingsmodule ab.',
                    'zh' => '本月完成所有可用的培训模块。',
                    'ru' => 'Заверши все доступные учебные модули в этом месяце.',
                    'hi' => 'इस महीने सभी उपलब्ध प्रशिक्षण मॉड्यूल पूरे करें।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'all_training_complete'],
                'target_count' => 1,
                'xp_reward' => 200,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 405,
            ],
            [
                'slug' => 'team_10_sales_month',
                'names' => [
                    'en' => 'Team 10 Sales',
                    'fr' => '10 Ventes d\'Équipe',
                    'es' => '10 Ventas de Equipo',
                    'pt' => '10 Vendas da Equipe',
                    'ar' => '10 مبيعات للفريق',
                    'de' => '10 Team-Verkäufe',
                    'zh' => '团队10笔销售',
                    'ru' => '10 командных продаж',
                    'hi' => 'टीम की 10 बिक्री',
                ],
                'descriptions' => [
                    'en' => 'Your team collectively makes 10 sales this month.',
                    'fr' => 'Ton équipe réalise collectivement 10 ventes ce mois-ci.',
                    'es' => 'Tu equipo realiza colectivamente 10 ventas este mes.',
                    'pt' => 'Sua equipe faz coletivamente 10 vendas este mês.',
                    'ar' => 'يحقق فريقك 10 عمليات بيع جماعية هذا الشهر.',
                    'de' => 'Dein Team erzielt diesen Monat gemeinsam 10 Verkäufe.',
                    'zh' => '你的团队本月集体完成10笔销售。',
                    'ru' => 'Твоя команда совместно совершает 10 продаж в этом месяце.',
                    'hi' => 'आपकी टीम इस महीने सामूहिक रूप से 10 बिक्री करे।',
                ],
                'type' => 'monthly',
                'criteria' => ['type' => 'team_sales_count', 'count' => 10],
                'target_count' => 10,
                'xp_reward' => 400,
                'bonus_cents' => 0,
                'is_secret' => false,
                'sort_order' => 406,
            ],

            // ── Secret (7) — type=one_time, is_secret=true ──────────
            [
                'slug' => 'lightning_start',
                'names' => [
                    'en' => 'Lightning Start',
                    'fr' => 'Départ Éclair',
                    'es' => 'Inicio Relámpago',
                    'pt' => 'Início Relâmpago',
                    'ar' => 'انطلاقة البرق',
                    'de' => 'Blitzstart',
                    'zh' => '闪电起步',
                    'ru' => 'Молниеносный старт',
                    'hi' => 'बिजली जैसी शुरुआत',
                ],
                'descriptions' => [
                    'en' => 'Make 3 sales within your first 24 hours.',
                    'fr' => 'Fais 3 ventes dans tes 24 premières heures.',
                    'es' => 'Haz 3 ventas en tus primeras 24 horas.',
                    'pt' => 'Faça 3 vendas nas suas primeiras 24 horas.',
                    'ar' => 'حقق 3 مبيعات خلال أول 24 ساعة.',
                    'de' => 'Mache 3 Verkäufe in deinen ersten 24 Stunden.',
                    'zh' => '在最初24小时内完成3笔销售。',
                    'ru' => 'Сделай 3 продажи в первые 24 часа.',
                    'hi' => 'पहले 24 घंटों में 3 बिक्री करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => '3_sales_first_day'],
                'target_count' => 3,
                'xp_reward' => 500,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 500,
            ],
            [
                'slug' => 'pentakill',
                'names' => [
                    'en' => 'Pentakill',
                    'fr' => 'Pentakill',
                    'es' => 'Pentakill',
                    'pt' => 'Pentakill',
                    'ar' => 'بنتاكيل',
                    'de' => 'Pentakill',
                    'zh' => '五杀',
                    'ru' => 'Пентакилл',
                    'hi' => 'पेंटाकिल',
                ],
                'descriptions' => [
                    'en' => 'Make 5 sales in a single day.',
                    'fr' => 'Fais 5 ventes en une seule journée.',
                    'es' => 'Haz 5 ventas en un solo día.',
                    'pt' => 'Faça 5 vendas em um único dia.',
                    'ar' => 'حقق 5 مبيعات في يوم واحد.',
                    'de' => 'Mache 5 Verkäufe an einem einzigen Tag.',
                    'zh' => '在一天内完成5笔销售。',
                    'ru' => 'Сделай 5 продаж за один день.',
                    'hi' => 'एक ही दिन में 5 बिक्री करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => '5_sales_1_day'],
                'target_count' => 5,
                'xp_reward' => 500,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 501,
            ],
            [
                'slug' => 'golden_mentor',
                'names' => [
                    'en' => 'Golden Mentor',
                    'fr' => 'Mentor d\'Or',
                    'es' => 'Mentor de Oro',
                    'pt' => 'Mentor de Ouro',
                    'ar' => 'المرشد الذهبي',
                    'de' => 'Goldener Mentor',
                    'zh' => '黄金导师',
                    'ru' => 'Золотой наставник',
                    'hi' => 'गोल्डन मेंटर',
                ],
                'descriptions' => [
                    'en' => 'One of your recruits earns $500 in total commissions.',
                    'fr' => 'Un de tes filleuls gagne 500$ de commissions totales.',
                    'es' => 'Uno de tus reclutas gana $500 en comisiones totales.',
                    'pt' => 'Um dos seus recrutados ganha $500 em comissões totais.',
                    'ar' => 'أحد المجنّدين لديك يكسب $500 من العمولات الإجمالية.',
                    'de' => 'Einer deiner Rekruten verdient $500 an Gesamtprovisionen.',
                    'zh' => '你的一位招募成员累计赚取$500佣金。',
                    'ru' => 'Один из твоих рекрутов заработает $500 общих комиссий.',
                    'hi' => 'आपका एक रिक्रूट कुल $500 कमीशन कमाए।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'referral_earned_500'],
                'target_count' => 1,
                'xp_reward' => 500,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 502,
            ],
            [
                'slug' => 'midnight_hustler',
                'names' => [
                    'en' => 'Midnight Hustler',
                    'fr' => 'Hustler de Minuit',
                    'es' => 'Guerrero Nocturno',
                    'pt' => 'Guerreiro da Madrugada',
                    'ar' => 'محارب منتصف الليل',
                    'de' => 'Mitternachts-Hustler',
                    'zh' => '午夜奋斗者',
                    'ru' => 'Полуночный хаслер',
                    'hi' => 'मिडनाइट हसलर',
                ],
                'descriptions' => [
                    'en' => 'Make a sale between midnight and 5 AM.',
                    'fr' => 'Fais une vente entre minuit et 5h du matin.',
                    'es' => 'Haz una venta entre medianoche y las 5 AM.',
                    'pt' => 'Faça uma venda entre meia-noite e 5h da manhã.',
                    'ar' => 'حقق عملية بيع بين منتصف الليل والخامسة صباحًا.',
                    'de' => 'Mache einen Verkauf zwischen Mitternacht und 5 Uhr morgens.',
                    'zh' => '在午夜到凌晨5点之间完成一笔销售。',
                    'ru' => 'Сделай продажу между полуночью и 5 утра.',
                    'hi' => 'आधी रात से सुबह 5 बजे के बीच एक बिक्री करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'night_sale'],
                'target_count' => 1,
                'xp_reward' => 100,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 503,
            ],
            [
                'slug' => 'phoenix',
                'names' => [
                    'en' => 'Phoenix',
                    'fr' => 'Phoenix',
                    'es' => 'Fénix',
                    'pt' => 'Fênix',
                    'ar' => 'العنقاء',
                    'de' => 'Phönix',
                    'zh' => '凤凰涅槃',
                    'ru' => 'Феникс',
                    'hi' => 'फ़ीनिक्स',
                ],
                'descriptions' => [
                    'en' => 'Come back and make a sale after 30 days of inactivity.',
                    'fr' => 'Reviens et fais une vente après 30 jours d\'inactivité.',
                    'es' => 'Vuelve y haz una venta después de 30 días de inactividad.',
                    'pt' => 'Volte e faça uma venda após 30 dias de inatividade.',
                    'ar' => 'عُد وحقق عملية بيع بعد 30 يومًا من عدم النشاط.',
                    'de' => 'Komm zurück und mache einen Verkauf nach 30 Tagen Inaktivität.',
                    'zh' => '在30天不活跃后回来完成一笔销售。',
                    'ru' => 'Вернись и сделай продажу после 30 дней неактивности.',
                    'hi' => '30 दिनों की निष्क्रियता के बाद वापस आएँ और बिक्री करें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'comeback_after_30d'],
                'target_count' => 1,
                'xp_reward' => 200,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 504,
            ],
            [
                'slug' => 'centurion',
                'names' => [
                    'en' => 'Centurion',
                    'fr' => 'Centurion',
                    'es' => 'Centurión',
                    'pt' => 'Centurião',
                    'ar' => 'القائد المئوي',
                    'de' => 'Zenturio',
                    'zh' => '百夫长',
                    'ru' => 'Центурион',
                    'hi' => 'सेंचुरियन',
                ],
                'descriptions' => [
                    'en' => 'Reach 100 total sales.',
                    'fr' => 'Atteins 100 ventes au total.',
                    'es' => 'Alcanza 100 ventas en total.',
                    'pt' => 'Alcance 100 vendas no total.',
                    'ar' => 'حقق 100 عملية بيع إجمالية.',
                    'de' => 'Erreiche 100 Verkäufe insgesamt.',
                    'zh' => '累计达到100笔销售。',
                    'ru' => 'Достигни 100 продаж в сумме.',
                    'hi' => 'कुल 100 बिक्री तक पहुँचें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'sales_count', 'count' => 100],
                'target_count' => 100,
                'xp_reward' => 500,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 505,
            ],
            [
                'slug' => 'mentor',
                'names' => [
                    'en' => 'Mentor',
                    'fr' => 'Mentor',
                    'es' => 'Mentor',
                    'pt' => 'Mentor',
                    'ar' => 'المرشد',
                    'de' => 'Mentor',
                    'zh' => '导师',
                    'ru' => 'Наставник',
                    'hi' => 'मेंटर',
                ],
                'descriptions' => [
                    'en' => 'Have 10 active recruits in your team.',
                    'fr' => 'Aie 10 filleuls actifs dans ton équipe.',
                    'es' => 'Ten 10 reclutas activos en tu equipo.',
                    'pt' => 'Tenha 10 recrutados ativos na sua equipe.',
                    'ar' => 'امتلك 10 مجنّدين نشطين في فريقك.',
                    'de' => 'Habe 10 aktive Rekruten in deinem Team.',
                    'zh' => '团队中拥有10名活跃招募成员。',
                    'ru' => 'Имей 10 активных рекрутов в своей команде.',
                    'hi' => 'अपनी टीम में 10 सक्रिय रिक्रूट रखें।',
                ],
                'type' => 'one_time',
                'criteria' => ['type' => 'active_referral_count', 'count' => 10],
                'target_count' => 10,
                'xp_reward' => 400,
                'bonus_cents' => 0,
                'is_secret' => true,
                'sort_order' => 506,
            ],
        ];

        foreach ($missions as $mission) {
            $isSecret = $mission['is_secret'];
            unset($mission['is_secret']);

            // Store is_secret flag inside criteria JSON since the column doesn't exist
            if ($isSecret) {
                $mission['criteria'] = array_merge($mission['criteria'], ['is_secret' => true]);
            }

            Mission::firstOrCreate(
                ['slug' => $mission['slug']],
                array_merge($mission, ['status' => 'active']),
            );
        }
    }
}
